// Community ideas are references for mechanisms, not evidence of current strength.
// Text below is our own checklist; historical item/rune lists are not copied.
export const RESEARCH_SOURCES={
 offmeta:{name:'Reddit · 娱乐下路讨论',url:'https://www.reddit.com/r/leagueoflegends/comments/1purqh1/offmeta_botlane_duo_recommendations/',kind:'community',checkedAt:'2026-10-04'},
 synergy:{name:'Reddit · 非常规下路联动',url:'https://www.reddit.com/r/supportlol/comments/1m13oo1/off_meta_bot_lane_synergy_ideas/',kind:'community',checkedAt:'2026-10-04'},
 botdiff:{name:'BOTDIFF · 非常规下路',url:'https://botdiff.lol/2025/11/04/top-off-meta-bot-lane-combinations-for-league-of-legends/',kind:'guide',checkedAt:'2026-10-04'},
 veigar:{name:'MOBAFire · 维迦下路指南',url:'https://www.mobafire.com/league-of-legends/build/trieuloos-challenger-in-depth-veigar-bot-guide-594691',kind:'guide',checkedAt:'2026-10-04'},
 taliyah:{name:'MOBAFire · 塔莉垭辅助指南',url:'https://www.mobafire.com/league-of-legends/build/taliyah-support-updated-s14-621554',kind:'guide',checkedAt:'2026-10-04'},
};
const rows=[
 ['Rammus','Yuumi','滚动猫车','wild','反普攻、承伤','龙龟负责近身承伤，悠米提供回复和保护。','面对普攻阵容再考虑；龙龟补刀，悠米辅助，先撑过清线期。','清线和远程补刀困难；对法术消耗阵容收益很低。','Orianna Kindred','botdiff'],
 ['Orianna','Malphite','魔偶快递','wild','魔偶运送、范围爆发','发条把球放在石头人身上，配合击飞衔接大招。','发条补刀，石头人辅助；先确认魔偶跟随距离，再约好六级进场。','双人前期较弱；魔偶脱离范围或控制被躲开时不要硬跟。','Graves JarvanIV','botdiff'],
 ['Anivia','Poppy','冰墙撞车','wild','造墙、地形控制','冰鸟造墙为波比 E 提供地形，后续衔接冰鸟控制。','冰鸟补刀，波比辅助；先找侧面角度，确认墙与目标的方向再撞。','造墙也会挡队友；站位、蓝量和兵线要求较高。','JarvanIV Graves','botdiff'],
 ['Brand','Nami','潮汐火焰','fun','法术增益、控制接力','娜美的增益和减速支持火男命中技能，控制可交错使用。','火男补刀，娜美辅助；先减速再找火男控制，泡泡可留作保护。','双脆皮、双法术；持续燃烧不等于无限触发娜美增益。','Shen Graves','botdiff'],
 ['Sion','Zilean','定时坦克','wild','炸弹载体、复活保护','基兰给敌方小兵挂炸弹，赛恩 E 将载体踢向对手；也可用赛恩控制接双炸弹。','赛恩补刀，基兰辅助；先约好挂弹小兵和踢兵方向，别同时清掉载体。复活提前预判集火。','不能保证每次踢兵都命中；手短，怕持续消耗与百分比伤害。','Kindred Orianna','offmeta'],
 ['Pantheon','Braum','盾击三连','fun','多段普攻、被动接控','潘森强化 W 的连续普攻帮助叠布隆被动。','潘森补刀，布隆辅助；先确认被动层数与强化技能，再一起集火。','近战补刀会受压；不能为追击丢掉布隆保护范围。','Orianna Sejuani','offmeta'],
 ['Galio','Senna','巨像护枪','wild','前排与射程、混合伤害','加里奥补刀撑住前排，赛娜以射程提供持续支援。','加里奥补刀，赛娜买辅助装；先用减速缩小走位空间再接控制。','加里奥清线耗蓝；面对强物理对线时要重新评估。','Kindred Graves','offmeta'],
 ['Taliyah','Senna','岩石与长枪','fun','减速接岩突、混合伤害','赛娜减速或禁锢后，塔莉垭更容易接岩突。','塔莉垭补刀，赛娜辅助；先确认控制命中再摆岩阵。','两人缺少稳定承伤；不要把岩突当必中的先手。','Shen Sejuani','offmeta'],
 ['Taliyah','Zyra','岩石花园','fun','定身接爆发、阵地战','婕拉定身给塔莉垭技能创造更清晰的落点。','塔莉垭补刀；植物布在撤退路径，定身命中后再接岩突。','双法术且容易推线，必须处理侧翼视野。','Graves JarvanIV','offmeta'],
 ['Taliyah','Neeko','岩石伪装','wild','定身接岩突、伪装先手','妮蔻先限制移动，塔莉垭接区域控制与伤害。','塔莉垭补刀；伪装只是寻找角度，先确认队友跟得上。','双脆皮；妮蔻不能因伪装就无视视野与伤害。','Graves Shen','offmeta'],
 ['Jhin','Taliyah','谢幕岩阵','wild','禁锢接技能、远程消耗','烬的 W 禁锢窗口可以帮助塔莉垭衔接岩突。','烬补刀，塔莉垭辅助；先造成标记再接 W，岩突用于接控或阻止突进。','两人技能空档明显，塔莉垭辅助经济有限。','Shen Sejuani','taliyah'],
 ['Nilah','Ivern','绿洲近战','wild','护盾回复、近战保护','翠神提供护盾与控制，帮助尼菈在近身窗口持续输出。','尼菈补刀，翠神辅助；围绕护盾冷却进退，先约好进场目标。','前期手短；翠神不是有护盾就能扛住所有爆发。','Galio JarvanIV','offmeta'],
 ['Quinn','Pyke','鹰眼鱼叉','wild','侧翼突袭、钩中集火','派克寻找控制窗口，奎因跟进短时爆发与游走。','奎因补刀；派克游走前先整理兵线，不要求两人一起离线。','对线失误后很难追经济；缺少传统后期火力。','Sejuani Orianna','offmeta'],
 ['Seraphine','Trundle','歌声石柱','wild','减速地形、控制接力','巨魔柱子的减速和地形帮助萨勒芬妮限制走位。','萨勒芬妮补刀，巨魔辅助；柱子先封退路，再接技能。','柱子可能妨碍队友；巨魔辅助缺经济，不能按上单装硬堆。','Graves Kindred','offmeta'],
 ['AurelionSol','Amumu','星河绷带','wild','范围限制、持续法术','阿木木先控制目标，为龙王持续施法创造时间。','龙王补刀，阿木木辅助；前期稳住，阿木木进场前确认龙王输出范围。','前期偏弱、全法术；施法会被突进打断。','Shen Graves','offmeta'],
 ['Urgot','Pantheon','近身火力','wild','点控接输出、压制接力','潘森点控帮助厄加特保持近身输出角度。','厄加特补刀，潘森辅助；先找稳定短换血，控制交错使用。','厄加特是远程英雄，但射程短；两人缺回复，落后时不要强行追击。','Orianna Sejuani','offmeta'],
 ['Kindred','Taric','双层保命圈','wild','保命窗口、延迟无敌','千珏大招争取塔里克大招生效的时间，需沟通先后顺序。','千珏补刀；提前约好大招节奏，先活过爆发再接第二层保护。','千珏大招也保护对手；塔里克大招延迟，不能保证无缝。','Orianna JarvanIV','offmeta'],
 ['Yone','Soraka','续航双刃','wild','回复保护、近战发育','索拉卡提供回复，永恩用作战窗口完成近身换血。','永恩补刀；先保住索拉卡站位，永恩回身后再补回复。','两人早期容易被消耗；索拉卡血量也是资源。','Sejuani Galio','offmeta'],
 ['Ekko','Zilean','时光双保险','wild','加速进场、回身保护','基兰加速支持艾克接近，复活作为额外保护。','艾克补刀；艾克先沟通回身点，基兰不用每次都跟入人群。','双法术且前期补刀难；两种保命都不能救所有失误。','Graves Shen','offmeta'],
 ['Naafiri','Leona','日光猎群','wild','定点接近、先手控制','蕾欧娜限制目标，为纳亚菲利接近创造机会。','纳亚菲利补刀；先消耗，再等蕾欧娜控制后跟进。','手短，怕保护与范围清场；辅助进场深度要克制。','Orianna Sejuani','offmeta'],
 ['Caitlyn','Nidalee','夹子标枪','wild','禁锢接标枪、攻速回复','女警夹子命中后，奈德丽更容易命中标枪并提供增益。','女警补刀，奈德丽辅助；先确认夹子禁锢，再从合适角度投标枪。','奈德丽缺稳定先手；别抢线或假定每发标枪命中。','Sejuani Shen','synergy'],
 ['Katarina','Amumu','绷带匕首','wild','范围控制、近身法术','阿木木限制移动，为卡特琳娜接近与输出提供窗口。','卡特补刀；先求安全发育，等对手打断技能使用后再跟进。','双近战压力大；阿木木控制并不能阻止所有打断。','Graves Shen','synergy'],
 ['TahmKench','Zac','弹跳双前排','wild','连续进场、承伤','扎克与塔姆可交错进场控制，轮流吸收压力。','塔姆补刀，扎克辅助；约好一人先手另一人留作保护。','持续火力不足，第三人需补输出；回复不是无限承伤。','Kindred Tristana','synergy'],
 ['Teemo','Shaco','陷阱游乐园','wild','区域陷阱、路线封锁','提莫蘑菇与萨科盒子为提前布置的区域增加威胁。','提莫补刀，萨科辅助；围绕入口和撤退路线布置，避免无视兵线。','清场和扫描会削弱阵地；缺前排与稳定开团。','Sejuani Galio','synergy'],
 ['Katarina','Sejuani','冰链匕首','wild','近战叠层、控制接力','近战队友可协助瑟庄妮叠层，为卡特提供接近窗口。','卡特补刀，瑟庄妮辅助；先控制再进，保留技能应对撤退。','两人前期手短；匕首技能伤害不等于全部都是普攻叠层。','Graves Orianna','synergy'],
 ['Viego','Sejuani','破败冰链','wild','多次普攻、连续控制','佛耶戈利用普攻节奏协助瑟庄妮叠层。','佛耶戈补刀，瑟庄妮辅助；先确认近身条件，再叠层接控制。','手短且依赖近身；不要为了变身窗口冲得过深。','Orianna Shen','synergy'],
 ['Mel','Neeko','双重定身','wild','远程控制、范围爆发','两人控制交错，给技能输出创造落点。','梅尔补刀，妮蔻辅助；先消耗再确认命中，保留一手保护。','双法术且脆弱；反射技能不能覆盖所有威胁。','Graves Shen','synergy'],
 ['Xerath','Velkoz','远程几何课','wild','远程消耗、接控','两位法师用远程技能限制走位，控制命中再补伤害。','泽拉斯补刀，维克兹辅助；避免同时交掉所有保护技能。','双脆皮、全法术；被贴脸时不能只继续蓄力。','Shen JarvanIV','synergy'],
 ['Lux','Velkoz','光束交叉','wild','定身接爆发、远程消耗','拉克丝定身与减速支持维克兹后续技能。','拉克丝补刀，维克兹辅助；控制错开，留意大招时的侧翼。','怕突进与打断；两人经济和清线要分工。','Shen Graves','synergy'],
 ['Poppy','Zilean','加速撞墙','wild','加速接近、地形控制','基兰加速支持波比找撞墙角度，并提供保命机会。','波比补刀，基兰辅助；有地形再进场，炸弹优先接控制。','远程补刀困难；空旷处不能指望 E 总能晕人。','Kindred Orianna','synergy'],
 ['Syndra','Zilean','定时法球','wild','控制接力、加速保护','辛德拉控制给基兰双炸弹更清晰的落点。','辛德拉补刀，基兰辅助；先保住走位，再交错限制目标。','双法术，命中要求高；不能把推球当作必中先手。','Graves Shen','synergy'],
 ['DrMundo','Lulu','巨大医生','wild','生命保护、近战承伤','璐璐保护与加速帮助蒙多接近并持续作战。','蒙多补刀，璐璐辅助；稳住血量，不为追人离开支援距离。','持续火力依赖其他人；面对重伤与百分比伤害仍需撤退。','Kindred Orianna','synergy'],
 ['Cassiopeia','Twitch','双毒追击','wild','中毒接输出、远程辅助','图奇施加中毒状态，蛇女利用状态窗口接双生毒牙。','蛇女补刀，图奇辅助；图奇先在安全位置挂毒，蛇女留蓝持续作战。','图奇辅助经济有限；没有前排时双人容易被突进。','Shen Sejuani','synergy'],
 ['Cassiopeia','Teemo','毒牙蘑菇','wild','中毒接输出、区域控制','提莫提供中毒状态，蛇女跟进持续法术输出。','蛇女补刀，提莫辅助；保持施法距离，毒与地形控制用于限制追击。','全法术、缺稳定先手；蛇女前期耗蓝很高。','Graves Shen','synergy'],
 ['Jhin','Nidalee','标枪谢幕','wild','技能标记、远程接控','奈德丽技能命中后，烬 W 可接禁锢，再寻找标枪角度。','烬补刀；先制造标记再接 W，奈德丽提供回复增益。','无可靠前排，烬装弹时不适合继续追击。','Sejuani Shen','synergy'],
 ['Veigar','Leona','日光牢笼','fun','先手接笼、控制延长','蕾欧娜先限制目标，维迦接笼子与技能。','维迦补刀；控制错开，给法师保持施法距离。','前期清线与蓝量有限，辅助别独自冲进远处。','Graves Shen','veigar'],
 ['Veigar','Nautilus','深海牢笼','fun','稳定接控、法术爆发','泰坦先限制目标，维迦借窗口布置区域控制。','维迦补刀；先稳住线，控制命中后接笼子和 W。','泰坦进场深时法师可能跟不上；缺普攻火力。','Kindred Graves','veigar'],
 ['Veigar','Thresh','灯笼牢笼','fun','撤退保护、连续控制','锤石控制帮助维迦布笼，灯笼增加撤退选择。','维迦补刀；优先接已命中的控制，灯笼放在能点到的位置。','不能每钩必中；蓝量和清线仍需管理。','Graves Shen','veigar'],
 ['Veigar','Pantheon','盾击牢笼','fun','点控接笼、短时爆发','潘森点控给维迦布置后续技能的时间。','维迦补刀；潘森辅助用低经济找接控机会，不抢清线资源。','过度追击会脱离法师射程；双人缺回复。','Shen Kindred','veigar'],
 ['Veigar','Zilean','时光牢笼','fun','区域接炸弹、加速保护','维迦限制活动区域，基兰衔接炸弹并保护法师走位。','维迦补刀；控制用于接力，加速可先用于撤退。','双法术且前期偏弱；炸弹命中仍需预判。','Graves JarvanIV','veigar'],
 ['Veigar','Soraka','回复牢笼','fun','回复保护、区域限制','索拉卡支持维迦续航，沉默与笼子交错限制区域。','维迦补刀；索拉卡站在安全位置，先保住血量再寻找控制衔接。','缺主动先手，怕集火索拉卡；需要第三人前排。','Sejuani Shen','veigar'],
 ['Veigar','Seraphine','和声牢笼','fun','区域控制、远程接力','笼子限制走位后，萨勒芬妮可接控制与远程伤害。','维迦补刀，萨勒芬妮辅助；不要同时把所有技能用来推线。','双法术、前期脆弱；经济需优先保证维迦发育。','Graves JarvanIV','veigar'],
 ['Seraphine','Anivia','冰上音乐会','wild','减速区域、控制接力','冰鸟提供减速与地形区域，为萨勒芬妮接控制创造空间。','萨勒芬妮补刀，冰鸟辅助；先约好墙的方向，避免挡住队友。','冰鸟辅助耗蓝且经济低；墙会影响双方走位。','Graves Shen','offmeta'],
 ['Yone','Yasuo','双刃接力','wild','击飞衔接、近战作战','永恩的击飞可为亚索提供大招衔接窗口。','永恩补刀，亚索辅助；约好击飞时机，先安全吃经验。','极低容错、双近战；辅助亚索缺经济，不宜当默认稳定方案。','Sejuani Galio','offmeta'],
 ['Teemo','Milio','暖炉毒箭','wild','射程增益、持续输出','米利欧提供射程和保护，帮助提莫保持普攻距离。','提莫补刀，米利欧辅助；输出时留在支援范围，蘑菇优先保护侧翼。','缺稳定先手与前排；射程增益不代表不会被突进。','Sejuani Shen','offmeta'],
];
export const COMMUNITY_DUOS=rows.map(([carry,support,name,style,tags,why,plan,risk,partners,source])=>({
 id:`${carry.toLowerCase()}-${support.toLowerCase()}`,carry,support,name,style,tags:tags.split('、'),why,plan,risk,partners:partners.split(' '),difficulty:style==='wild'?'较高':'适中',
 sources:[RESEARCH_SOURCES[source]],evidence:'社区玩法启发 · 机制人工复核',reviewedAt:'2026-10-04',patch:'16.19',
}));
export const COMMUNITY_LINKS=COMMUNITY_DUOS.map(d=>[d.carry,d.support,d.why]);
