const {app,BrowserWindow}=require('electron');
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(process.env.RIFT_BUDDY_USER_DATA);
const windows=[];app.on('browser-window-created',(_event,win)=>windows.push(win));
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(check,label){for(let n=0;n<100;n++){const result=await check();if(result)return result;await delay(100);}throw Error(label);}
async function run(){
 const release=JSON.parse(await fs.readFile('release/latest.json','utf8'));
 require(process.env.RIFT_BUDDY_SOURCE==='1'?path.resolve('electron/main.cjs'):path.join(release.directory,'resources/app.asar/electron/main.cjs'));
 const main=await until(()=>windows.find(w=>!w.isDestroyed()&&w.webContents.getURL().endsWith('/src/index.html')),'Main window missing');
 await until(()=>main.webContents.executeJavaScript('!!window.buddy&&!!document.querySelector("[data-action=guide-current]")'),'Main UI missing');
 const mainJS=code=>main.webContents.executeJavaScript(code,true);
 await mainJS(`window.buddy.openGuide({id:'Ashe',role:'bottom',mode:'rift',coreIndex:0,conditions:[],augmentIds:[]})`);
 const guide=await until(()=>windows.find(w=>!w.isDestroyed()&&w.webContents.getURL().endsWith('/src/guide.html')),'Guide window missing');
 const guideJS=code=>guide.webContents.executeJavaScript(code,true);
 const painted=async js=>{await js('Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))).then(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))))');await delay(150);};
 await until(()=>guideJS('!!document.querySelector(".route-item")'),'Guide items missing');
 await until(()=>guide.isVisible(),'Guide was not shown');assert.equal(guide.isAlwaysOnTop(),true);
 await until(()=>guideJS('[...document.images].every(i=>i.complete&&i.naturalWidth>0)'),'Guide local images missing');
 await painted(guideJS);await fs.writeFile(path.join(root,'guide-rift.png'),(await guide.webContents.capturePage()).toPNG());
 const before=await guideJS('window.guide.bootstrap()');
 assert.ok(before.model.purchase.length);assert.equal(before.model.live.matched,false);
 if(before.model.collapsed)await guideJS("window.guide.control('collapse')");
 await guideJS('{const d=document.querySelector("details[data-guide-section=route]");d.open=true;}');
 await guideJS('document.querySelector("main").scrollTop=90');
 const scroll=await guideJS('document.querySelector("main").scrollTop');assert.ok(scroll>0);
 const first=before.model.route[0].id;
 const marked=await guideJS(`window.guide.control('item',${JSON.stringify(first)})`);
 assert.deepEqual(marked.model.completedItems,[first]);assert.notEqual(marked.model.next?.id,first);
 assert.equal(await guideJS('document.querySelector("main").scrollTop'),scroll);
 const collapse=await guideJS("window.guide.control('collapse')");assert.equal(collapse.model.collapsed,true);assert.ok(Math.abs(guide.getSize()[1]-220)<=2);
 await guideJS("window.guide.control('opacity',0.85)");assert.equal(guide.getOpacity(),.85);
 await guideJS("window.guide.control('collapse')");
 await guideJS("window.guide.control('hide')");assert.equal(guide.isVisible(),false);
 await mainJS('window.buddy.openGuide()');assert.equal(guide.isVisible(),true);
 const reopen=await guideJS('window.guide.bootstrap()');assert.deepEqual(reopen.model.completedItems,[first]);
 const rejected=await guideJS("window.guide.control('arbitrary').then(()=>false,()=>true)");assert.equal(rejected,true);
 await mainJS(`window.buddy.openGuide({id:'Ashe',role:'bottom',mode:'hex',coreIndex:0,conditions:[],augmentIds:[]})`);
 const hex=await guideJS('window.guide.bootstrap()');assert.equal(hex.model.runes.length,0);assert.equal(hex.model.augments.length,5);assert.equal(hex.model.completedItems.length,0);
 await guideJS('document.querySelector("[data-tab=augments]").click()');
 await until(()=>guideJS('!!document.querySelector(".augment")'),'Hex augment tab missing');
 await until(()=>guideJS('[...document.images].every(i=>i.complete&&i.naturalWidth>0)'),'Hex images missing');
 await painted(guideJS);await fs.writeFile(path.join(root,'guide-hex.png'),(await guide.webContents.capturePage()).toPNG());
 await mainJS(`window.buddy.openGuide({id:'Ashe',role:'bottom',mode:'hex',compareIds:[1048,1002,1141],ownedAugmentIds:[1047]})`);
 await until(()=>guideJS('document.querySelector("main").textContent.includes("本次选项比较")'),'Guide comparison missing');
 const fresh=await guideJS("window.guide.control('new-game')");assert.equal(fresh.model.comparison.length,0);assert.equal(fresh.model.completedItems.length,0);assert.equal(fresh.model.selection.ownedAugmentIds,undefined);
 await guideJS("window.guide.control('main')");
 await until(()=>mainJS('!!document.querySelector("[data-action=open-guide]")'),'Guide return to full config failed');
 await painted(mainJS);await fs.writeFile(path.join(root,'main-config.png'),(await main.webContents.capturePage()).toPNG());
 main.close();await guideJS("window.guide.control('main')");
 const replacement=await until(()=>windows.find(w=>w!==main&&w!==guide&&!w.isDestroyed()&&w.webContents.getURL().endsWith('/src/index.html')),'Closed main did not reopen');
 await until(()=>replacement.webContents.executeJavaScript('!!document.querySelector("[data-action=open-guide]")'),'Reopened main missed guide selection');
 const saved=JSON.parse(await fs.readFile(path.join(root,'settings.json'),'utf8'));
 assert.equal(saved.preferences.autoSync,false);assert.equal(saved.preferences.autoCheck,false);assert.equal(saved.guide.selection.mode,'hex');
 const result={passed:true,source:process.env.RIFT_BUDDY_SOURCE==='1'?'working-tree':'packaged',packagedArchive:process.env.RIFT_BUDDY_SOURCE==='1'?null:release.archiveSha256,alwaysOnTop:true,manualPurchase:true,collapsed:true,opacity:true,hideReopen:true,hexAugments:true,noRuneWrite:true,returnToConfiguration:true,userPreferencesPreserved:true,screenshots:root};
 await fs.writeFile(path.join(root,'guide-smoke.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));app.quit();
}
run().catch(async error=>{console.error(error);await fs.writeFile(path.join(root,'guide-smoke-error.txt'),error.stack).catch(()=>{});app.exit(1);});
