const {app,dialog,globalShortcut,session}=require('electron'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),https=require('node:https'),cp=require('node:child_process'),{EventEmitter}=require('node:events');
const windows=[],root=path.resolve(process.env.RIFT_BUDDY_USER_DATA),delay=ms=>new Promise(r=>setTimeout(r,ms));app.on('browser-window-created',(_e,w)=>{windows.push(w);w.show=()=>{};w.showInactive=()=>{};w.focus=()=>{};w.webContents.setBackgroundThrottling(false);});
globalShortcut.register=()=>false;global.fetch=async()=>{throw Error('Isolated import smoke: network disabled');};https.request=()=>{throw Error('Isolated import smoke: LCU disabled');};
const realSpawn=cp.spawn;cp.spawn=(file,...args)=>{if(!file.endsWith('window-observer.exe'))return realSpawn(file,...args);const child=new EventEmitter();child.stdout=new EventEmitter();child.stdout.setEncoding=()=>{};child.stdin={end(){child.exitCode=0;child.emit('exit',0);}};child.kill=()=>child.stdin.end();return child;};
app.whenReady().then(()=>session.defaultSession.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']},(_details,callback)=>callback({cancel:true})));
async function until(check,label){for(let n=0;n<150;n++){const v=await check();if(v)return v;await delay(100);}throw Error(label);}
async function run(){
 const source=process.env.RIFT_BUDDY_SOURCE==='1',release=JSON.parse(await fs.readFile('release/latest.json','utf8')),base=source?path.resolve('.'):path.join(release.directory,'resources/app.asar');let file='old-backup.json';
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path.join(root,file)]});require(path.join(base,'electron/main.cjs'));
 const main=await until(()=>windows.find(w=>w.webContents.getURL().endsWith('/src/index.html')),'Main missing'),js=c=>main.webContents.executeJavaScript(c,true);await until(()=>js('!!document.querySelector("[data-action=recommend]")'),'UI missing');
 const click=async sel=>{assert.ok(await js(`!!document.querySelector(${JSON.stringify(sel)})`),sel);await js(`document.querySelector(${JSON.stringify(sel)}).click()`);};
 await click('[data-action=draft-scope][data-scope=bot]');await click('[data-action=recommend]');await until(()=>js('document.querySelectorAll(".result-card").length>0'),'Initial strict-pool recommendations missing');
 await click('[data-action=navigate][data-route=settings]');await click('[data-action=import]');await until(async()=>JSON.parse(await fs.readFile(path.join(root,'settings.json'))).preferences.style==='balanced','Old import did not finish');
 const old=(await js('window.buddy.bootstrap()')).state.preferences;assert.deepEqual(old.pool,['Ashe','Nami']);assert.equal(old.poolMode,'only');assert.equal(old.rolePools.bottom.mode,'only');assert.equal(old.autoLive,false);assert.equal(old.guideAutoShow,false);assert.equal(old.guideAfterGame,'keep');
 await click('[data-action=navigate][data-route=draft]');assert.equal(await js('document.querySelectorAll(".result-card").length'),0);await click('[data-action=recommend]');await until(()=>js('!!document.querySelector(".result-card")'),'Second results missing');
 // Import a newer strict-pool backup after viewing an older recommendation.
 await click('[data-action=result-detail]');await click('[data-action=navigate][data-route=settings]');file='new-backup.json';await click('[data-action=import]');await until(async()=>JSON.parse(await fs.readFile(path.join(root,'settings.json'))).preferences.pool.includes('Caitlyn'),'New import did not finish');
 assert.equal(await js('document.querySelectorAll(".result-card").length'),0);const state=(await js('window.buddy.bootstrap()')).state;assert.deepEqual(state.preferences.pool,['Caitlyn','Lux']);assert.equal(state.preferences.rolePools.bottom.heroes[0],'Caitlyn');
 await click('[data-action=navigate][data-route=draft]');await click('[data-action=recommend]');await until(()=>js('!!document.querySelector(".result-card")'),'New pool cannot recommend');await click('[data-action=result-detail]');await click('[data-action=use-result]');
 await until(()=>js('window.buddy.bootstrap().then(b=>b.state.draft?.slots?.find(s=>s.role==="bottom")?.champion==="Caitlyn")'),'Accepted draft was not persisted');const applied=(await js('window.buddy.bootstrap()')).state.draft.slots;assert.equal(applied.find(s=>s.role==='bottom').champion,'Caitlyn');assert.equal(applied.find(s=>s.role==='support').champion,'Lux');assert.equal(state.ownedPageId,null);
 const capacity={...(await js('window.buddy.bootstrap()')).state,favorites:Array.from({length:499},(_,i)=>({id:'kept-'+i,type:'build',title:'原收藏 '+i,champion:'Ashe',role:'bottom',mode:'rift'})),preparations:Array.from({length:499},(_,i)=>({id:'Ashe',role:'bottom',mode:'rift',comboId:'test-'+i}))};
 await js('window.buddy.saveState('+JSON.stringify(capacity)+')');await new Promise(resolve=>{main.webContents.once('did-finish-load',resolve);main.webContents.reload();});await until(()=>js('!!document.querySelector("[data-action=navigate]")'),'Capacity reload missing');await click('[data-action=navigate][data-route=settings]');
 const before=(await js('window.buddy.bootstrap()')).state,beforeBytes=await fs.readFile(path.join(root,'settings.json'));
 const newFavorite=id=>({id,type:'build',title:id,champion:'Ashe',role:'bottom',mode:'rift'}),newPreparation=i=>({id:'Ashe',role:'bottom',mode:'rift',comboId:'test-'+i});
 for(const [kind,favorites,preparations]of [['favorites',[newFavorite('new-a'),newFavorite('new-b')],[]],['preparations',[newFavorite('new-a')],[newPreparation(499),newPreparation(500)]]]){
  file=kind+'-overflow.json';await fs.writeFile(path.join(root,file),JSON.stringify({schema:1,favorites,preparations,excluded:[],preferences:{style:'wild'}}));await js('document.querySelector("#toast").textContent=""');await click('[data-action=import]');await until(()=>js('document.querySelector("#toast").textContent.includes("整次导入已取消")'),'Overflow import not explained: '+kind);
  assert.deepEqual((await js('window.buddy.bootstrap()')).state,before);assert.deepEqual(await fs.readFile(path.join(root,'settings.json')),beforeBytes);
 }
 file='deduplicated-capacity.json';await fs.writeFile(path.join(root,file),JSON.stringify({schema:1,favorites:[{...before.favorites[0],title:'备份冲突'},newFavorite('new-a'),newFavorite('new-a')],preparations:[{...before.preparations[0],coreIndex:2},newPreparation(499)],excluded:[],preferences:{style:'balanced'}}));await click('[data-action=import]');
 await until(()=>js('document.querySelector("#toast").textContent.includes("已合并收藏与配置")'),'Deduplicated boundary import failed');const merged=(await js('window.buddy.bootstrap()')).state;assert.equal(merged.favorites.length,500);assert.equal(merged.preparations.length,500);assert.equal(merged.favorites[0].title,before.favorites[0].title);assert.equal(merged.preparations[0].coreIndex,0);assert.equal(merged.preferences.style,'balanced');assert.deepEqual(JSON.parse(await fs.readFile(path.join(root,'settings.json'),'utf8')),merged);assert.ok(windows.every(w=>!w.isVisible()));
 const result={passed:true,source:source?'working-tree':'packaged',archiveSha256:source?null:release.archiveSha256,realImportIPC:true,oldBackupPreservesMissingPreferences:true,newBackupRestoresExplicitPreferences:true,oldRecommendationsInvalidated:true,newStrictPoolApplied:true,wholeImportRejectedAtBothCapacityLimits:true,originalMemoryDiskAndPreferencesPreserved:true,deduplicationAllowsExactCapacity:true,actualRuneWrites:false,userSettingsIsolated:true,testWindowsHidden:true};await fs.writeFile(path.join(root,'import-smoke.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));app.quit();
}
run().catch(e=>{console.error(e);app.exit(1);});
