const {app,ipcMain,session}=require('electron'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const windows=[],root=path.resolve(process.env.RIFT_BUDDY_USER_DATA),delay=ms=>new Promise(r=>setTimeout(r,ms));app.on('browser-window-created',(_e,w)=>{windows.push(w);w.show=()=>{};w.showInactive=()=>{};w.focus=()=>{};});global.fetch=async()=>{throw Error('Isolated journey offline');};require('node:https').request=()=>{throw Error('Real game sockets prohibited');};app.whenReady().then(()=>session.defaultSession.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']},(_d,c)=>c({cancel:true})));
async function until(check,label){for(let n=0;n<150;n++){const v=await check();if(v)return v;await delay(100);}throw Error(label);}
async function run(){
 const source=process.env.RIFT_BUDDY_SOURCE==='1',release=JSON.parse(await fs.readFile('release/latest.json','utf8')),base=source?path.resolve('.'):path.join(release.directory,'resources/app.asar');
 const originalHandle=ipcMain.handle.bind(ipcMain),originalData=JSON.parse(await fs.readFile(path.join(base,'data/game.json'))),refs=JSON.parse(await fs.readFile(path.join(base,'data/builds.json'))).entries;
 const parts=originalData.patch.split('.').map(Number),nextPatch=parts[0]+'.'+(parts[1]+1);
 let client={connected:true,phase:'ChampSelect',mode:{id:'rift',label:'召唤师峡谷'},message:'测试快照',receivedAt:new Date().toISOString(),session:{allowDuplicatePicks:false,theirTeam:[{cellId:6,championId:51}],bans:[22],myTeam:[{cellId:1,championId:59,assignedPosition:'BOTTOM'},{cellId:2,championId:267,assignedPosition:''}],localPlayerCellId:1}},runeWrites=0,runtimeData,patch=originalData.patch,refreshCalls=[],oldRelease;
 ipcMain.handle=(channel,handler)=>originalHandle(channel,channel==='bootstrap'?async(...args)=>{const boot=await handler(...args);runtimeData=structuredClone(boot.data);return boot;}:channel==='client-status'?async()=>client:channel==='apply-runes'?async()=>{runeWrites++;return {name:'隔离测试符文',pageId:777};}:channel==='refresh-build'?async(_event,id,role)=>{const captured=patch;refreshCalls.push({id,role,patch:captured});if(refreshCalls.length===1)await new Promise(r=>oldRelease=r);return {...refs[id+':'+role],patch:captured,fetchedAt:new Date().toISOString()};}:channel==='update-data'?async()=>{assert(runtimeData?.catalog?.version,'Version mock requires the full runtime snapshot');patch=nextPatch;return {data:{...runtimeData,patch,version:nextPatch+'.1',builds:{},buildSources:{},hexBuilds:{}}};}:handler);
 require(path.join(base,'electron/main.cjs'));
 const main=await until(()=>windows.find(w=>w.webContents.getURL().endsWith('/src/index.html')),'Main missing'),js=c=>main.webContents.executeJavaScript(c,true);
 await until(()=>js('!!document.querySelector(".party-summary")'),'Draft missing');ipcMain.handle=originalHandle;
 const click=async sel=>{assert.ok(await js(`!!document.querySelector(${JSON.stringify(sel)})`),sel);await js(`document.querySelector(${JSON.stringify(sel)}).click()`);};
 const capture=async name=>{await js('Promise.all([...document.images].map(i=>{i.loading="eager";return i.decode().catch(()=>{});})).then(()=>new Promise(r=>requestAnimationFrame(r)))');await fs.writeFile(path.join(root,name),(await main.webContents.capturePage()).toPNG());};
 await click('[data-action=reset-draft]');assert.ok(await js('document.querySelector(".party-summary").textContent.includes("上路、打野、辅助")'));
 await click('[data-action=pick-slot][data-role=support]');await js('{const i=document.querySelector("#picker-search");i.value="皇子";i.dispatchEvent(new Event("input",{bubbles:true}));}');assert.ok(await js('!!document.querySelector(".picker-fallback")'));await click('[data-action=pick-champion][data-id=JarvanIV]');
 await click('[data-action=sync]');await until(()=>js('document.querySelector("[data-drop-role=support] .slot-meta").textContent.includes("手动位置")'),'Manual first sync unbound');
 client={...client,session:{...client.session,myTeam:[{cellId:1,championId:202,assignedPosition:'BOTTOM'},{cellId:2,championId:267,assignedPosition:''}]}};await click('[data-action=sync]');await until(()=>js('document.querySelector("[data-drop-role=support] .champ-name").textContent.includes("烬")'),'Client replacement not followed');
 await click('[data-action=my-build]');assert.equal(await js('document.querySelector("#build-role").value'),'support','My build ignored the explicit manual preparation position');await click('[data-action=close]');assert.ok(await js('document.querySelector("[data-drop-role=support] .champ-name").textContent.includes("烬")'),'Opening formal build moved the analysis board');
 await click('[data-action=clear-slot][data-role=support]');assert.ok(await js('!!document.querySelector(".unassigned [data-id=Jhin]")'));assert.ok(await js('document.querySelector(".draft-preferences summary").textContent.includes("公开禁选 1")'));
 await click('[data-action=reset-draft]');assert.equal(await js('document.querySelectorAll(".unassigned [data-drag-cell]").length'),2);assert.ok(await js('document.querySelector(".draft-preferences summary").textContent.includes("不可镜像 1")'));await capture('draft-position-ownership.png');
 const savedClient=client;client={...client,session:{...client.session,myTeam:[],theirTeam:[],bans:[]}};await click('[data-action=sync]');await click('[data-action=reset-draft]');
 const setPool=async(role,id)=>{await click('[data-action=role-pools]');await js(`{const i=document.querySelector('[data-role-pool-mode=${role}]');i.value='only';i.dispatchEvent(new Event('change',{bubbles:true}));}`);await click(`[data-action=role-pool-edit][data-role=${role}]`);await js(`{const i=document.querySelector('#picker-search');i.value=${JSON.stringify(id)};i.dispatchEvent(new Event('input',{bubbles:true}));}`);await click(`[data-action=pick-champion][data-id=${id}]`);await click('[data-action=close]');};
 await setPool('bottom','Ashe');await setPool('support','Ashe');await click('[data-action=draft-scope][data-scope=bot]');await click('[data-action=recommend]');await until(()=>js('!!document.querySelector(".recommendation-error")'),'Empty-combination failure not persistent');assert.ok(await js('!!document.querySelector(".recommendation-error [data-action=role-pools]")'));
 await setPool('support','Nami');await click('[data-action=recommend]');await until(()=>js('!!document.querySelector(".result-card")'),'Adjusted pool did not recover');assert.equal(await js('document.querySelector(".recommendation-error")'),null);client=savedClient;await click('[data-action=sync]');
 await click('[data-action=navigate][data-route=settings]');assert.ok(await js('document.querySelector("#guide-after-game").value==="hide"'));await js('{const i=document.querySelector("#guide-after-game");i.value="collapse";i.dispatchEvent(new Event("change",{bubbles:true}));}');await until(async()=>JSON.parse(await fs.readFile(path.join(root,'settings.json'))).preferences.guideAfterGame==='collapse','End behavior not saved');
 main.webContents.send('open-build',{id:'Ashe',role:'bottom',mode:'rift'});await until(()=>js('!!document.querySelector(".preparation-summary")'),'Preparation summary missing');
 assert.ok(await js('document.querySelector(".preparation-summary").textContent.includes("国服版本未核实")'));assert.ok(await js('document.querySelector(".preparation-summary").textContent.includes("应用对象仍是你自己的客户端")'));
 await click('[data-action=apply-runes]');await until(()=>js('document.querySelector(".preparation-summary").textContent.includes("本次已应用这套选择")'),'Application summary not updated');assert.equal(runeWrites,1);
 await click('.rune-option:not(.active)');assert.ok(await js('document.querySelector(".preparation-summary").textContent.includes("尚未应用")'));await capture('preparation-summary.png');
 // UI-level version turnover with deterministic source mocks: old response arrives after fresh data.
 if(await js("!!document.querySelector('[data-action=\"build-loadout\"][data-id=\"default\"]')"))await click('[data-action="build-loadout"][data-id="default"]');await click('[data-action=auto-check]');await click('[data-action=refresh-build]');await until(()=>!!oldRelease,'Old configuration request missing');await click('[data-action=update]');await until(()=>js(`document.querySelector(".preparation-summary").textContent.includes(${JSON.stringify('基础资料 '+nextPatch+'.1')})`),'New data version missing');assert.equal(refreshCalls.length,1,'Rift update must not implicitly fetch a configuration');await click('[data-action=refresh-build]');await until(()=>refreshCalls.some(c=>c.patch===nextPatch),'Explicit new-patch request missing');
 oldRelease();await delay(300);await fs.writeFile(path.join(root,'refresh-diagnostic.json'),JSON.stringify({refreshCalls,summary:await js('document.querySelector(".preparation-summary").textContent'),source:await js('document.querySelector("[data-build-source-status]").textContent'),activeLoadout:await js('document.querySelector(".loadout-option.active")?.textContent||null')},null,2));await until(()=>js(`document.querySelector(".preparation-summary").textContent.includes(${JSON.stringify('当前配置 '+nextPatch)})`),'Fresh configuration missing');assert.equal(refreshCalls.length,2);assert.equal(runeWrites,1);await capture('updated-configuration-status.png');
 const result={passed:true,source:source?'working-tree':'packaged',archiveSha256:source?null:release.archiveSha256,clearPreservesParty:true,clearPreservesPublicConstraints:true,singleClearKeepsPublicPick:true,persistentEmptyResultRecovery:true,offRoleSearch:true,firstSyncBindsAndFollows:true,myBuildUsesManualRole:true,formalClientRoleUnchanged:true,manualBoardPreservedAfterBuild:true,lifecyclePreferenceSaved:true,preparationSummary:true,runeTargetExplicit:true,runeSelectionInvalidatesApplied:true,riftConfigurationRefreshedExplicitlyAfterVersionChange:true,lateOldResponseRejected:true,networkSourcesMocked:true,actualRuneWrites:false,screenshots:root};
 await fs.writeFile(path.join(root,'journey-smoke.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));app.quit();
}
run().catch(e=>{console.error(e);app.exit(1);});
