const {app,ipcMain}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const windows=[],root=path.resolve(process.env.RIFT_BUDDY_USER_DATA);app.on('browser-window-created',(_e,w)=>windows.push(w));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(check,label){for(let i=0;i<150;i++){const r=await check();if(r)return r;await delay(100);}throw Error(label);}
async function run(){
 app.setPath('userData',root);
 const https=require('node:https'),dns=require('node:dns/promises'),{EventEmitter}=require('node:events');let releaseMaintenance;
 let runeWrites=0;const copies=[];ipcMain.handle('copy',(_event,value)=>{copies.push(value);return true;});
 const register=ipcMain.handle.bind(ipcMain);let pauseMutation='',releaseMutation,personalCalls=0,failPersonal=false;
 ipcMain.handle=(channel,handler)=>channel==='copy'?undefined:channel==='apply-runes'?register(channel,()=>{runeWrites++;throw Error('Real rune writes prohibited in catalog smoke');}):register(channel,['catalog-apply','catalog-rollback','catalog-personal'].includes(channel)?async(...args)=>{if(channel==='catalog-personal'){personalCalls++;if(failPersonal){failPersonal=false;throw Error('测试保存失败');}}if(pauseMutation===channel)await new Promise(r=>releaseMutation=r);return handler(...args);}:handler);
 dns.lookup=async()=>[{address:'8.8.8.8',family:4}];
 https.request=(url,options,callback)=>{assert.equal(new URL(url).hostname,'ddragon.leagueoflegends.com');const req=new EventEmitter();req.end=()=>{releaseMaintenance=()=>{const res=new EventEmitter();res.statusCode=200;res.resume=()=>{};callback(res);res.emit('data',Buffer.from('["16.19.1"]'));res.emit('end');req.emit('close');};};req.destroy=e=>{if(e)req.emit('error',e);req.emit('close');};return req;};
 const source=process.env.RIFT_BUDDY_SOURCE==='1',release=JSON.parse(await fs.readFile('release/latest.json','utf8'));
 require(source?path.resolve('electron/main.cjs'):path.join(release.directory,'resources/app.asar/electron/main.cjs'));
 const main=await until(()=>windows.find(w=>w.webContents.getURL().endsWith('/src/index.html')),'Main missing'),js=code=>main.webContents.executeJavaScript(code,true);
 const reload=()=>new Promise(resolve=>{main.webContents.once('did-finish-load',resolve);main.webContents.reload();});
 await until(()=>js('!!document.querySelector("[data-action=role-pools]")'),'Draft missing');
 const click=async selector=>{assert.ok(await js(`!!document.querySelector(${JSON.stringify(selector)})`),selector);await js(`document.querySelector(${JSON.stringify(selector)}).click()`);await delay(70);};
 const set=async(selector,value,event='input')=>js(`{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event(${JSON.stringify(event)},{bubbles:true}));}`);
 const pointerClick=async selector=>{
  const point=await js(`{const el=document.querySelector(${JSON.stringify(selector)}),r=el.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;({x,y,visible:r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth,hit:el.contains(document.elementFromPoint(x,y))});}`);
  assert.equal(point.visible,true,selector+' outside viewport');assert.equal(point.hit,true,selector+' blocked');
  const zoom=main.webContents.getZoomFactor(),x=Math.round(point.x*zoom),y=Math.round(point.y*zoom);
  main.webContents.sendInputEvent({type:'mouseMove',x,y});main.webContents.sendInputEvent({type:'mouseDown',x,y,button:'left',clickCount:1});main.webContents.sendInputEvent({type:'mouseUp',x,y,button:'left',clickCount:1});await delay(100);
 };
 const boot=()=>js('window.buddy.bootstrap()');
 const capture=async name=>{main.show();main.focus();main.webContents.focus();main.webContents.setBackgroundThrottling(false);await until(()=>js('([...document.images].forEach(i=>i.loading="eager"),[...document.images].every(i=>i.complete&&i.naturalWidth>0))'),'Current images did not load: '+name);await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');await fs.writeFile(path.join(root,name),(await main.webContents.capturePage()).toPNG());};
 ipcMain.removeHandler('refresh-build');ipcMain.handle('refresh-build',()=>({updated:false,reason:'测试离线配置'}));
 const initial=await boot();assert.ok(initial.data.catalog.trios.length>=68);
 await click('[data-action=navigate][data-route=settings]');await capture('catalog-manager.png');await click('[data-action=catalog-json]');
 const pack=structuredClone(initial.data.catalog);pack.version='2026.10.05.smoke';pack.name='实测独立组合库';pack.notes='新增三人套路与专用配置。';
 pack.loadouts.push({...pack.loadouts.find(l=>l.id==='trio-ball'),id:'smoke-galio',name:'测试加里奥接团路线',champions:['Galio'],runes:['comet','aftershock']});
 const trio={...pack.trios.find(t=>t.id==='camille-galio-vi'),id:'smoke-shen-jarvan-galio',name:'测试三人援护',members:[{role:'top',champion:'Shen',job:'跨图保护',loadoutId:'trio-frontline'},{role:'jungle',champion:'JarvanIV',job:'先手限制',loadoutId:'default'},{role:'mid',champion:'Galio',job:'后续支援',loadoutId:'smoke-galio'}]};pack.trios.push(trio);
 await set('#catalog-json',JSON.stringify(pack));await click('[data-action=catalog-validate]');await until(()=>js('!!document.querySelector(".catalog-change-list")'),'Preview missing');assert.equal((await boot()).data.catalog.version,initial.data.catalog.version);await capture('catalog-preview.png');await click('[data-action=catalog-apply]');await until(async()=> (await boot()).data.catalog.version===pack.version,'Apply failed');
 await click('[data-action=navigate][data-route=draft]');await click('[data-action=combination-library]');await click('[data-action=combo-kind][data-kind=trios]');await set('#combo-search','测试三人');assert.equal(await js('document.querySelectorAll(".combo-row").length'),1);await js('document.querySelector(".combo-row details").open=true');await capture('trio-library.png');
 await click('[data-action=combo-member][data-id=Galio]');await until(()=>js('document.querySelector(".loadout-option.active")?.dataset.id==="smoke-galio"'),'New loadout not active');assert.ok(await js('document.querySelectorAll(".rune-option").length>=2'));assert.equal(await js('document.querySelectorAll("[data-action=build-partner]").length'),2);await click('[data-action=open-guide]');
 const guide=await until(()=>windows.find(w=>w.webContents.getURL().endsWith('/src/guide.html')),'Guide missing');await until(()=>guide.webContents.executeJavaScript('document.body.textContent.includes("测试加里奥")'),'Guide catalog not synchronized');await guide.webContents.executeJavaScript("window.guide.control('hide')");await click('[data-action=close]');
 // Exercise the friendly editor, including the no-submit/reload behavior.
 await click('[data-action=navigate][data-route=settings]');await click('[data-action=catalog-edit]');await set('[name=name]','自己收藏的三人配合');await set('[name=tempo]','growth','change');
 for(const [i,role,id,job] of [[0,'top','Shen','前排保护'],[1,'jungle','JarvanIV','先手限制'],[2,'mid','Galio','后续支援']]){await set(`[name="role-${i}"]`,role,'change');await set(`[name="hero-${i}"]`,id,'change');await set(`[name="job-${i}"]`,job);}
 for(const [field,value] of Object.entries({why:'用前排与支援接住先手。',plan:'先确认支援距离\n皇子先手，慎和加里奥跟进',risk:'不要离开支援距离。',window:'关键大招可用时。',early:'先保证兵线和经验。',economy:'各自使用位置经济，辅助优先视野。'}))await set(`[name="${field}"]`,value);
 await capture('custom-editor.png');const beforeDoubleSave=personalCalls;await js('{const b=document.querySelector("[data-action=catalog-save]");b.click();b.click();}');await until(async()=> (await boot()).data.catalogInfo.personalCount===1,'Custom save failed');await until(()=>js('!document.querySelector("#catalog-form")'),'Double save left editor open');assert.equal(personalCalls-beforeDoubleSave,1,'Fast double save submitted more than once');assert.ok(await js('!!document.querySelector(".catalog-panel")'));await click('[data-action=catalog-rollback]');await until(async()=> (await boot()).data.catalog.version===initial.data.catalog.version,'Rollback failed');assert.equal((await boot()).data.catalogInfo.personalCount,1);assert.ok((await boot()).data.catalog.trios.some(t=>t.name==='自己收藏的三人配合'));
 // The same protection must apply when creating a new duo with generated IDs.
 await click('[data-action=catalog-edit]');await click('[data-action=catalog-editor-kind][data-kind=duo]');const duoCarry='Ashe',duoSupport=initial.data.champions.find(h=>h.id!==duoCarry&&!initial.data.catalog.duos.some(d=>d.carry===duoCarry&&d.support===h.id)).id;
 for(const [field,value] of Object.entries({name:'快速保存的新下路组合','role-0':'bottom','role-1':'support','hero-0':duoCarry,'hero-1':duoSupport,'job-0':'下路负责补刀','job-1':'辅助按实际技能支持搭档',window:'双方技能与输出距离确认后',early:'先安全获取经验',economy:'下路补刀，辅助支援',why:'用于验证个人下路编辑器。',plan:'先沟通控制与补刀。',risk:'仅作为个人整理，不代表胜率。'}))await set('[name="'+field+'"]',value,/^(hero|role)-/.test(field)?'change':'input');
 const beforeNewDuo=personalCalls;await js('{const b=document.querySelector("[data-action=catalog-save]");b.click();b.click();}');await until(async()=> (await boot()).data.catalogInfo.personalCount===2,'New duo double save failed');await until(()=>js('!document.querySelector("#catalog-form")'),'New duo double save left editor open');assert.equal(personalCalls-beforeNewDuo,1);assert.equal((await boot()).data.catalog.duos.filter(c=>c.name==='快速保存的新下路组合').length,1);
 // Cross-lane editing uses actual positions and normal mouse saving at small sizes.
 await click('[data-action=catalog-edit]');await click('[data-action=catalog-editor-kind][data-kind=duo]');
 const editorLayouts=[];
 for(const [width,height,zoom]of [[1448,945,1],[1100,720,1.25],[900,600,1.25]]){
  main.setContentSize(width,height);main.webContents.setZoomFactor(zoom);main.webContents.setBackgroundThrottling(false);main.focus();main.webContents.focus();await delay(250);await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
  await js('document.querySelector("#catalog-form").scrollTop=0');
  const metrics=await js('({viewport:[innerWidth,innerHeight],body:(()=>{const e=document.querySelector("#catalog-form"),r=e.getBoundingClientRect();return {x:r.left+8,y:r.top+r.height/2,top:r.top,bottom:r.bottom,client:e.clientHeight,scroll:e.scrollHeight,overflow:getComputedStyle(e).overflowY};})(),button:(()=>{const e=document.querySelector("[data-action=catalog-save]"),r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom,hit:e.contains(document.elementFromPoint(r.left+r.width/2,r.top+r.height/2))};})()})');
  assert.ok(metrics.body.client>0&&metrics.body.scroll>metrics.body.client);assert.equal(metrics.body.overflow,'auto');assert.ok(metrics.button.top>=0&&metrics.button.bottom<=metrics.viewport[1]);assert.equal(metrics.button.hit,true);
  await capture(`editor-before-${width}-${height}-${zoom}.png`);await js('window.lastEditorWheel=null;document.addEventListener("wheel",e=>window.lastEditorWheel={x:e.clientX,y:e.clientY,target:e.target.tagName,deltaY:e.deltaY},{once:true,passive:true})');
  main.webContents.sendInputEvent({type:'mouseMove',x:Math.round(metrics.body.x*zoom),y:Math.round(metrics.body.y*zoom)});await delay(100);main.webContents.sendInputEvent({type:'mouseWheel',x:Math.round(metrics.body.x*zoom),y:Math.round(metrics.body.y*zoom),deltaY:-450,hasPreciseScrollingDeltas:true,canScroll:true});
  await delay(150);await fs.writeFile(path.join(root,'editor-input-diagnostic.json'),JSON.stringify({width,height,zoom,...metrics,focused:main.isFocused(),wheel:await js('window.lastEditorWheel'),scrollTop:await js('document.querySelector("#catalog-form").scrollTop')},null,2));
  await until(()=>js('document.querySelector("#catalog-form").scrollTop>40'),'Normal wheel did not scroll the editor');
  const scrollTop=await js('document.querySelector("#catalog-form").scrollTop');editorLayouts.push({width,height,zoom,...metrics,scrollTop});await capture(`editor-${width}-${height}-${zoom}.png`);
  await js('document.querySelector("[name=source]").focus()');main.webContents.sendInputEvent({type:"keyDown",keyCode:"Tab"});main.webContents.sendInputEvent({type:"keyUp",keyCode:"Tab"});await until(()=>js('document.activeElement?.dataset.action==="catalog-save"'),"Keyboard could not reach save");
 }
 main.setContentSize(1100,720);main.webContents.setZoomFactor(1.25);await delay(180);
 for(const [field,value]of Object.entries({name:'我们的野中接力','role-0':'jungle','hero-0':'Graves','job-0':'保持输出距离，接实际命中控制，失败回到刷野','role-1':'mid','hero-1':'Ahri','job-1':'中线能离开再用魅惑接应搭档',why:'处理好经济再约同一目标',plan:'双方到场后阿狸确认魅惑命中\n格雷福斯接输出，空了各自返回经济',risk:'距离断开或技能落空就不追',window:'实际技能可用且两人有退路',early:'中路先处理兵线，打野先完成刷野路线',economy:'中路补刀，打野刷野；不长期分享同一波兵'}))await set('[name="'+field+'"]',value,/^(hero|role)-/.test(field)?'change':'input');
 await js('document.querySelector("#catalog-form").scrollTop=0');await until(()=>js('!document.querySelector("#toast.show")'),'Previous notification did not clear');await capture('cross-lane-editor.png');await pointerClick('[data-action=catalog-save]');await until(async()=> (await boot()).data.catalogInfo.personalCount===3,'Cross-lane mouse save failed');
 main.setContentSize(1200,860);main.webContents.setZoomFactor(1);await delay(180);
 const customPair=(await boot()).data.catalog.duos.find(d=>d.name==='我们的野中接力');assert.ok(customPair);assert.deepEqual(customPair.members.map(m=>m.role),['jungle','mid']);assert.equal(customPair.carry,undefined);
 await click('[data-action=navigate][data-route=draft]');await click('[data-action=combination-library]');await set('#combo-search','我们的野中');assert.equal(await js('document.querySelectorAll(".combo-row").length'),1);await js('document.querySelector(".combo-row details").open=true');await capture('cross-lane-library.png');
 await click(`.combo-row [data-action=build][data-id=Graves]`);await until(()=>js('document.querySelector(".drawer")?.textContent.includes("我们的野中接力")'),'Cross-lane build missing');assert.equal(await js('document.querySelectorAll("[data-action=build-partner]").length'),1);await click('[data-action=open-guide]');await until(()=>guide.webContents.executeJavaScript('document.body.textContent.includes("格雷福斯")'),'Cross-lane guide missing');await guide.webContents.executeJavaScript('document.querySelector("[data-tab=team]").click()');await until(()=>guide.webContents.executeJavaScript('document.body.textContent.includes("保持输出距离，接实际命中控制，失败回到刷野")'),'Personal job not in guide');await guide.webContents.executeJavaScript('window.guide.control("hide")');await click('[data-action=build-partner][data-id=Ahri]');await until(()=>js('document.querySelector(".drawer")?.textContent.includes("阿狸")'),'Partner did not use actual mid role');await click('[data-action=close]');
 await click('[data-action=combination-library]');await set('#combo-search','我们的野中');await click(`[data-action=catalog-edit-entry][data-id="${customPair.id}"]`);await set('[name=risk]','距离断开或魅惑落空就返回各自经济');await pointerClick('[data-action=catalog-save]');await until(async()=> (await boot()).data.catalog.duos.find(d=>d.id===customPair.id)?.risk==='距离断开或魅惑落空就返回各自经济','Cross-lane edit did not persist');customPair.risk='距离断开或魅惑落空就返回各自经济';
 await click('[data-action=draft-scope][data-scope=party]');for(const role of ['jungle','bottom','support'])await click(`[data-action=toggle-party][data-role=${role}]`);
 const beforeLoad=(await boot()).state.draft.slots;await click('[data-action=combination-library]');await set('#combo-search','我们的野中');await click(`[data-action=load-duo][data-id="${customPair.id}"]`);await until(async()=> (await boot()).state.draft.slots.some(s=>s.role==='mid'&&s.champion==='Ahri'),'Personal pair load failed');const loaded=(await boot()).state.draft;assert.equal(loaded.scope,'party');assert.ok(loaded.slots.some(s=>s.role==='jungle'&&s.champion==='Graves'));for(const role of ['top','bottom','support'])assert.deepEqual(loaded.slots.find(s=>s.role===role),beforeLoad.find(s=>s.role===role));
 await click('[data-action=recommend]');await until(()=>js('document.querySelector(".result-card")?.textContent.includes("我们的野中接力")'),'Loaded personal plan missing');await click('[data-action=result-detail]');await click('[data-action=copy-result]');assert.ok(copies.at(-1).includes(customPair.members[0].job));await click('.plan-drawer [data-action=favorite-result]');await until(async()=> (await boot()).state.favorites.some(f=>f.title==='我们的野中接力'),'Personal team favorite missing');await click('[data-action=close]');
 await reload();await until(()=>js('!!document.querySelector("[data-action=role-pools]")'),'Cross-lane restart missing');const restarted=(await boot()).data.catalog.duos.find(d=>d.id===customPair.id);assert.deepEqual(restarted,customPair);
 await click('[data-action=navigate][data-route=favorites]');const favorite=(await boot()).state.favorites.find(f=>f.title==='我们的野中接力');assert.equal(favorite.configurations.length,2);assert.ok(favorite.configurations.every(c=>c.comboId===customPair.id));await click('[data-action=open-favorite]');await until(()=>js('!!document.querySelector("[data-action=role-pools]")'),'Favorite load failed');await click('[data-action=build][data-id=Ahri][data-role=mid]');await until(()=>js('document.querySelector("[data-build-section=combo]")?.textContent.includes("中线能离开再用魅惑接应搭档")'),'Favorite lost authored member job');await click('[data-action=close]');
 await click('[data-action=navigate][data-route=settings]');

 // An edit to one visible field must preserve richer JSON source metadata.
 const rich={...initial.data.catalog.duos[0],id:'local-rich-editor',name:'多来源个人套路',style:'wild',patch:'16.18',reviewedAt:'2026-09-25',tags:['朋友自制'],partners:['Ahri'],sources:[{name:'第一来源',url:'https://example.com/one',kind:'个人收藏',checkedAt:'2026-10-01'},{name:'第二来源',url:'https://example.com/two',kind:'个人收藏',checkedAt:'2026-10-02'}]};
 await js(`window.buddy.catalogPersonal(${JSON.stringify(rich)})`);await reload();await until(()=>js('!!document.querySelector("[data-action=role-pools]")'),'Rich editor reload missing');
 await click('[data-action=combination-library]');await click('[data-action=combo-kind][data-kind=duos]');await set('#combo-search','多来源个人');await click('[data-action=catalog-edit-entry][data-id=local-rich-editor]');await set('[name=risk]','仅更改这一条短板说明');await click('[data-action=catalog-save]');
 await until(async()=> (await boot()).data.catalog.duos.find(d=>d.id===rich.id)?.risk==='仅更改这一条短板说明','Rich custom edit failed');const edited=(await boot()).data.catalog.duos.find(d=>d.id===rich.id);
 for(const key of ['style','tags','partners','sources','patch','reviewedAt'])assert.deepEqual(edited[key],rich[key],`Editing risk lost ${key}`);
 await capture('personal-metadata-preserved.png');
 await click('[data-action=combination-library]');await click('[data-action=combo-kind][data-kind=duos]');await set('#combo-search','多来源个人');await click('[data-action=catalog-edit-entry][data-id=local-rich-editor]');await js('{const c=document.querySelector("[name=review-current]");c.checked=true;c.dispatchEvent(new Event("change",{bubbles:true}));}');await click('[data-action=catalog-save]');await until(async()=> (await boot()).data.catalog.duos.find(c=>c.id===rich.id).patch===initial.data.patch,'Explicit personal review did not update its patch');assert.notEqual((await boot()).data.catalog.duos.find(c=>c.id===rich.id).reviewedAt,rich.reviewedAt);
 // Saving a custom entry follows the same rule when the user starts a new draft.
 await click('[data-action=combination-library]');await click('[data-action=combo-kind][data-kind=duos]');await set('#combo-search','多来源个人');await click('[data-action=catalog-edit-entry][data-id=local-rich-editor]');await capture('explicit-personal-review.png');await set('[name=risk]','延迟保存的风险提醒');pauseMutation='catalog-personal';releaseMutation=null;await click('[data-action=catalog-save]');await until(()=>!!releaseMutation,'Delayed personal save missing');await click('[data-action=close]');await click('[data-action=navigate][data-route=settings]');await click('[data-action=catalog-json]');await set('#catalog-json','自定义保存期间的新草稿');releaseMutation();await until(async()=> (await boot()).data.catalog.duos.find(c=>c.id===rich.id).risk==='延迟保存的风险提醒','Delayed personal save did not finish');await delay(120);assert.equal(await js('document.querySelector("#catalog-json")?.value'),'自定义保存期间的新草稿','Old personal save closed a new editor');pauseMutation='';await click('[data-action=close]');
 // A type switch starts a new form while an old save is still in flight.
 await click('[data-action=navigate][data-route=draft]');
 await click('[data-action=combination-library]');await click('[data-action=combo-kind][data-kind=duos]');await set('#combo-search','多来源个人');await click('[data-action=catalog-edit-entry][data-id=local-rich-editor]');await set('[name=risk]','类型切换前保存的提醒');pauseMutation='catalog-personal';releaseMutation=null;const beforeDuoDouble=personalCalls;await js('{const b=document.querySelector("[data-action=catalog-save]");b.click();b.click();}');await until(()=>!!releaseMutation,'Type switch save fixture missing');assert.equal(personalCalls-beforeDuoDouble,1,'Duo save submitted more than once');assert.equal(await js('document.querySelector("[data-action=catalog-save]").disabled'),true);
 await click('[data-action=catalog-editor-kind][data-kind=trio]');await set('[name=name]','切换类型后的新草稿');releaseMutation();await until(async()=> (await boot()).data.catalog.duos.find(c=>c.id===rich.id).risk==='类型切换前保存的提醒','Old duo save did not finish');await delay(120);assert.equal(await js('document.querySelector("[name=name]")?.value'),'切换类型后的新草稿','Old save closed a changed-kind draft');assert.equal(await js('document.querySelectorAll(".catalog-members fieldset").length'),3);assert.equal(await js('document.querySelector("[data-action=catalog-save]").disabled'),false);pauseMutation='';await click('[data-action=close]');
 // A failed save must unlock its original form and retain its text for retry.
 await click('[data-action=combination-library]');await click('[data-action=combo-kind][data-kind=duos]');await set('#combo-search','多来源个人');await click('[data-action=catalog-edit-entry][data-id=local-rich-editor]');await set('[name=risk]','失败后应保留的文字');failPersonal=true;await click('[data-action=catalog-save]');await until(()=>js('document.querySelector("[data-action=catalog-save]")?.disabled===false'),'Failed save did not unlock');assert.equal(await js('document.querySelector("[name=risk]").value'),'失败后应保留的文字');assert.notEqual((await boot()).data.catalog.duos.find(c=>c.id===rich.id).risk,'失败后应保留的文字');await click('[data-action=catalog-save]');await until(async()=> (await boot()).data.catalog.duos.find(c=>c.id===rich.id).risk==='失败后应保留的文字','Save retry failed');
 // A slow maintenance response must not cover or invalidate a newer JSON edit.
 await click('[data-action=navigate][data-route=settings]');await click('[data-action=catalog-check]');await until(()=>!!releaseMaintenance,'Maintenance fixture was not requested');
 await click('[data-action=catalog-json]');const newer=structuredClone((await boot()).data.catalog);newer.name='维护期间编辑的新组合库';newer.notes='仅改变元数据，保持原版本';await set('#catalog-json',JSON.stringify(newer));await click('[data-action=catalog-validate]');await until(()=>js('document.querySelector(".modal-header")?.textContent.includes("维护期间编辑")'),'Newer metadata preview missing');
 releaseMaintenance();await delay(350);assert.ok(await js('document.querySelector(".modal-header")?.textContent.includes("维护期间编辑")'),'Older maintenance response replaced newer editor');assert.equal(await js('document.querySelector("[data-action=catalog-apply]").disabled'),false);
 await click('[data-action=catalog-apply]');await until(async()=> (await boot()).data.catalog.name===newer.name,'Newer metadata preview cannot be applied');
 // A completed old mutation must not discard a newer editor's unsaved text.
 await click('[data-action=catalog-json]');const delayed=structuredClone((await boot()).data.catalog);delayed.version='delayed-apply';await set('#catalog-json',JSON.stringify(delayed));await click('[data-action=catalog-validate]');pauseMutation='catalog-apply';releaseMutation=null;await click('[data-action=catalog-apply]');await until(()=>!!releaseMutation,'Delayed apply missing');
 await click('[data-action=catalog-json]');const unsaved='尚未保存的另一份草稿';await set('#catalog-json',unsaved);releaseMutation();await until(async()=> (await boot()).data.catalog.version===delayed.version,'Delayed apply did not finish');await delay(180);assert.equal(await js('document.querySelector("#catalog-json")?.value'),unsaved,'Old apply closed a newer editor');pauseMutation='';await click('[data-action=close]');
 pauseMutation='catalog-rollback';releaseMutation=null;await click('[data-action=catalog-rollback]');await until(()=>!!releaseMutation,'Delayed rollback missing');await click('[data-action=catalog-json]');await set('#catalog-json',unsaved);releaseMutation();await until(async()=> (await boot()).data.catalog.version===initial.data.catalog.version,'Delayed rollback did not finish');await delay(180);assert.equal(await js('document.querySelector("#catalog-json")?.value'),unsaved,'Old rollback closed a newer editor');pauseMutation='';await click('[data-action=close]');
 // Worker reload, single-member replacement, role pools, and stale-reading card.
 await click('[data-action=navigate][data-route=draft]');await click('[data-action=role-pools]');await set('[data-role-pool-mode=mid]','prefer','change');await click('[data-action=role-pool-edit][data-role=mid]');await click('[data-action=pick-champion][data-id=Orianna]');await click('[data-action=close]');await click('[data-action=example]');await click('[data-action=recommend]');await until(()=>js('document.querySelectorAll(".result-card").length===3'),'Worker missing');await click('[data-action=result-detail]');await capture('trio-play-card.png');await click('[data-action=replace-member][data-role=mid]');await until(()=>js('document.querySelector(".drawer-content").textContent.includes("其他位置不变")||document.querySelector(".drawer-content").textContent.includes("替换后")'),'Replacement missing');await click('[data-action=close]');
 await click('[data-action=result-detail]');ipcMain.removeHandler('client-status');ipcMain.handle('client-status',()=>({connected:true,phase:'ChampSelect',message:'测试选人数据更新',session:{myTeam:[{cellId:1,championId:103,assignedPosition:'MIDDLE'}],theirTeam:[],bans:[],localPlayerCellId:1}}));await click('[data-action=sync]');await until(()=>js('document.querySelector("#result-stale")?.hidden===false'),'Stale card missing');assert.equal(await js('document.querySelector("[data-action=use-result]").disabled'),true);await capture('stale-play-card.png');await click('[data-action=close]');
 const final=await boot();assert.equal(final.state.preferences.rolePools.mid.mode,'prefer');assert.deepEqual(final.state.preferences.rolePools.mid.heroes,['Orianna']);
 // Reload the actual main window to confirm the persisted catalog and personal overlay.
 await reload();await until(()=>js('!!document.querySelector("[data-action=role-pools]")'),'Reload failed');const reloaded=await boot();assert.equal(reloaded.data.catalogInfo.personalCount,4);assert.equal(reloaded.data.catalog.version,initial.data.catalog.version);assert.ok(reloaded.data.catalog.trios.some(t=>t.name==='自己收藏的三人配合'));
 assert.equal(reloaded.data.catalog.trios.find(t=>t.name==='自己收藏的三人配合').tempo,'growth');await click('[data-action=combination-library]');await click('[data-action=combo-kind][data-kind=trios]');await set('#combo-search','自己收藏的三人');await set('#combo-tempo','growth','change');assert.equal(await js('document.querySelectorAll(".combo-row").length'),1);
 assert.equal(runeWrites,0);const result={actualRuneWrites:runeWrites,passed:true,source:source?'working-tree':'packaged',archiveSha256:source?null:release.archiveSha256,previewInert:true,applyLive:true,guideLive:true,customEditor:true,growthEditorAndFilter:true,crossLanePersonalPair:true,editorLayouts,singleFlightPersonalSave:true,typeSwitchDraftPreserved:true,failedSaveRetry:true,personalMetadataPreserved:true,concurrentPreviewPreserved:true,metadataOnlyUpdate:true,lateMutationPreservesNewDraft:true,explicitPersonalReview:true,rollbackPreservesPersonal:true,worker:true,partialReplacement:true,rolePools:true,staleReadingCard:true,reload:true,noRuneWrites:true,screenshots:root};await fs.writeFile(path.join(root,'catalog-smoke.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));app.quit();
}
run().catch(async e=>{console.error(e);await fs.writeFile(path.join(root,'catalog-smoke-error.txt'),e.stack).catch(()=>{});app.exit(1);});
