import {stateRecoveryView} from './state-recovery-view.mjs';
import {localPickEligibility} from './core/pick-eligibility.mjs';
import {pickEligibilityView} from './pick-eligibility-view.mjs';
import {summonerSelector} from './summoner-selection-view.mjs';
import {cooperationView,resultActionsView,resultMemberJobs} from './cooperation-view.mjs';
import {pairStatisticsView} from './pair-statistics-view.mjs';
import {pairRefreshTargets,pairRefreshView} from './pair-refresh-view.mjs';
import {teamWindowsView} from './team-windows-view.mjs';
import {opponentFitView} from './opponent-fit-view.mjs';
import {itemSetControls} from './item-sets-view.mjs';
import {matchupPreparationView} from './matchup-preparation-view.mjs';
import {matchupPreparation} from './core/matchup-preparation.mjs';
import {heroCoach} from './core/hero-coach.mjs';
import {buildSourceControls} from './build-source-view.mjs';
import {heroCoachView} from './hero-coach-view.mjs';
import {duoPlayView} from './duo-play-view.mjs';
import {runeComparisonView} from './rune-comparison-view.mjs';
import {matchupView} from './matchup-view.mjs';
import {matchupTargetView} from './matchup-plan-view.mjs';
import {publicMatchupOpponent} from './core/matchup-plans.mjs';
import {escape as e,portrait,asset,button,gameDescription} from './ui.mjs';
import {ROLES,STYLES} from './core/rules.mjs';
import {SHARDS,featuredRuneOptions} from './core/builds.mjs';
import {laterItemSelector,bottomQuestPlanControl,gearSelector} from './build-options-view.mjs';
import {DRAFT_SCOPES,scopeSlots,clientDraftStatus,CLIENT_POSITION_ROLES,manualPlayerSlot} from './core/draft.mjs';
import {analyzeTeam} from './core/recommend.mjs';
import {corePurpose} from './draft-result-view.mjs';
import {findSavedBuild} from './core/build-favorites.mjs';
const roleName=id=>ROLES.find(r=>r.id===id)?.name||'位置待确认';
const planKey=s=>[s.id,s.role,s.mode].join(':');
const conditions=[['ad','普攻压力'],['ap','魔法伤害'],['control','控制多'],['heal','回血多'],['burst','容易被秒']];

const sampleLabel=(o,source=o.source,scope='完整页')=>o.samples>0?`${o.samples.toLocaleString()} 场来源样本${o.samples<200?' · 样本较少':''}${Number.isFinite(o.winRate)?' · 胜率 '+o.winRate.toFixed(1)+'%':''}${Number.isFinite(o.pickRate)?' · 使用率 '+o.pickRate.toFixed(1)+'%':''}`:source==='OP.GG'?`OP.GG 来源参考 · ${scope}样本未提供`:'机制备选 · 无统计样本';
function coreComparison(b,data,key){
 const options=b.reference?.core||[];
 if(options.length<2)return '';
 return `<details class="companion-core-options" data-companion-disclosure="core"><summary>比较核心路线 · ${options.length} 套来源备选</summary><p>比较常用核心三件。用途按装备机制整理，来源样本不代表这套符文与装备的联合胜率。</p><div class="companion-comparisons" aria-label="核心路线比较">${options.slice(0,3).map((c,n)=>`<button class="companion-option ${n===b.selectedCoreIndex?'active':''}" data-action="companion-core" data-id="${n}" data-plan="${key}" aria-pressed="${n===b.selectedCoreIndex}"><b>${e(corePurpose(c,data))}${n===b.selectedCoreIndex?'<em>已选</em>':''}</b><div class="companion-option-items">${c.items.map(id=>asset('item',id,data.items[id]?.name)).join('')}</div><small>${e(c.items.map(id=>data.items[id]?.name||'旧版装备').join(' → '))}</small><small>${e(sampleLabel(c,b.reference?.source,"核心路线"))}</small></button>`).join('')}</div></details>`;
}
function runeComparison(b,options,runes,key,data){
 return `<div class="companion-comparisons" aria-label="常用符文比较">${options.map(o=>`<button class="companion-option ${o.id===b.selectedRuneId?'active':''}" data-action="companion-rune" data-id="${e(o.id)}" data-plan="${key}" aria-pressed="${o.id===b.selectedRuneId}"><b><span class="rune-option-title">${asset('rune',o.page.selectedPerkIds[0],runes.get(o.page.selectedPerkIds[0])?.name)}${e(o.name)}</span>${o.id===b.selectedRuneId?'<em>已选</em>':''}</b><small>${e(o.when||'完整方案可在下方核对')}</small>${runeComparisonView(o.page,b.runePage,data)}<small>${e(sampleLabel(o))}</small></button>`).join('')}</div>`;
}

function companionPlanSummary(b,data,runes){
 const core=b.items.slice(0,3),perks=b.runePage?.selectedPerkIds||[],keystone=runes.get(perks[0]);
 const source=b.reference&&b.loadoutId==='default'?`OP.GG ${b.rulesPatch}${b.referenceStale?' · 旧版本':''}`:`机制整理 ${b.rulesPatch}${b.stale?' · 待复核':''}`;
 return `<section class="companion-plan-summary" aria-label="当前搭配摘要"><div class="companion-summary-title"><b>当前搭配</b><small>${e(source)}</small></div><button class="companion-summary-core" data-action="companion-jump" data-section="items" aria-label="查看完整出装路线">${core.map(i=>`<span>${asset('item',i.id,i.name)}<small>${e(i.name)}</small></span>`).join('')}</button>${b.runePage?`<button class="companion-summary-runes" data-action="companion-jump" data-section="runes" aria-label="查看当前完整符文页">${asset('rune',perks[0],keystone?.name)}<span><b>${e(keystone?.name||b.selectedRune?.name)}</b><small>${perks.slice(1,6).map(id=>e(runes.get(id)?.name||'')).filter(Boolean).join(' · ')}</small></span></button>`:`<p>${b.mode==='hex'?'海克斯强化按局内选项决定':'完整符文暂不可用'}</p>`}<button class="companion-summary-skills" data-action="companion-jump" data-section="skills">${b.priority?`加点 ${e(b.priority.split('').join(' › '))}`:'加点按游戏内机制确认'}${b.first?` · 前三级 ${e(b.first.split('').join(' › '))}`:''}</button></section>`;
}

export function companionPlanView(data,plan,favorites=[],{refreshing=false,error='',enemyIds=[],opponentId='',matchupStatus='',publicContext='',itemSetStatuses=new Map()}={}){
 if(!plan)return '<div class="companion-empty">选好英雄后自动准备方案。也可以在推荐卡片中预览装备、符文和加点。</div>';
 const {build:b,selection:s}=plan,key=e(planKey(s)),runes=new Map(data.runes.flatMap(t=>t.slots.flatMap(slot=>slot.runes.map(r=>[r.id,r]))));
 const opponent=publicMatchupOpponent(data,enemyIds,opponentId),coach=s.mode==='rift'?heroCoach({data,champion:s.id,role:s.role,priority:b.priority,enemyId:opponent?.id,combo:b.combo,stage:b.combo?'key':'opening'}):null;
 const saved=!!findSavedBuild(favorites,{...s,conditions:s.conditions||[],coreIndex:b.selectedCoreIndex||0,build:b});
 const baseline=b.runeOptions[0]?.page.selectedPerkIds||[];
 const featured=featuredRuneOptions(b.runeOptions);
 if(b.selectedRune&&!featured.includes(b.selectedRune)){featured.unshift(b.selectedRune);featured.splice(3);}
 const ordered=[...featured,...b.runeOptions.filter(o=>!featured.includes(o))];
 const runeChoices=ordered.map((o,i)=>{const changes=o.page.selectedPerkIds.filter((id,n)=>id!==baseline[n]).map(id=>runes.get(id)?.name||SHARDS[id]).filter(Boolean);return {...o,name:`${i+1}. ${o.name}${o.id===b.runeOptions[0].id?' · 默认参考':changes.length?' · '+changes.slice(0,2).join(' / '):''}${o.samples>0?' · '+o.samples.toLocaleString()+' 场':o.source==='OP.GG'?' · 来源参考':' · 机制备选'}`};});
 const select=(field,label,options,selected)=>`<label>${label}<select class="select" data-companion-field="${field}" data-plan="${key}">${options.map(o=>`<option value="${e(o.id)}" ${String(o.id)===String(selected)?'selected':''}>${e(o.name)}</option>`).join('')}</select></label>`;
 const items=(list,ordered=false)=>{
  const grouped=new Map();for(const i of list){const current=grouped.get(String(i.id));if(current)current.count++;else grouped.set(String(i.id),{item:i,count:1});}
  const rows=ordered?list.map(item=>({item,count:1})):[...grouped.values()];
  return `<div class="companion-items">${rows.map(({item:i,count},n)=>`<div title="${e(gameDescription(i.description))}">${asset('item',i.id,i.name)}<span>${ordered?`<em>${n+1}</em>`:''}<b>${e(i.name)}${count>1?' × '+count:''}</b><small>${Number.isFinite(i.gold?.total)?i.gold.total*count+' 金':'价格待确认'}${i.purchaseBase?' · 升级装备':''}</small></span></div>`).join('')}</div>`;
 };
 const primary=data.runes.find(t=>t.id===b.runePage?.primaryStyleId),secondary=data.runes.find(t=>t.id===b.runePage?.subStyleId);
 return `${plan.preview?`<div class="companion-preview" ${plan.intent?'data-pick-intent="true"':''}><b>${plan.intent?'正在预选':'预览'} ${e(data.champions.find(c=>c.id===s.id)?.name)} · ${roleName(s.role)}</b><small>${plan.intent?(plan.positionKnown?'尚未选定，选定后保留这套调整。':'位置未确认，暂按此位置查看；可在上方修改。'):'仅查看方案，请在客户端自己选择英雄。'}</small>${plan.intent?button('companion-tab','查看英雄推荐','','quiet small','data-tab="recommend"'):button('companion-current','返回我的方案','','quiet small')}</div>`:''}<nav class="companion-plan-nav" aria-label="方案内容">${[['items','装备'],['runes','符文'],['skills','加点'],...(s.mode==='rift'?[['opponent','对手']]:[]),...(b.combo?.play?[['combo','配合']]:[])].map(([id,label])=>button('companion-jump',label,'','small',`data-section="${id}"`)).join('')}</nav>${companionPlanSummary(b,data,runes)}<div class="companion-row-actions"><span>装备、符文与加点可独立选择</span>${button('companion-favorite',saved?'已收藏 · 点击取消':'收藏当前搭配','star',`quiet small ${saved?'saved':''}`,`data-plan="${key}" aria-pressed="${saved}"`)}</div>
 ${refreshing||error?`<p class="companion-refresh-state ${error?'text-gold':''}" role="status">${refreshing?'正在刷新来源，当前方案仍可查看。':'刷新未完成，保留当前参考：'+e(error)}</p>`:''}
 ${s.mode==='rift'?buildSourceControls(data,{reference:b.reference,champion:s.id,role:s.role,refreshing,companion:true,plan:planKey(s)}):''}
 ${b.referenceStale?`<p class="companion-source-banner" title="旧方案保留，可继续使用；出装按实际局势调整。">基础资料 ${e(data.patch)} · OP.GG ${e(b.rulesPatch)} 旧版本参考</p>`:''}
 ${b.loadoutOptions.length?select('loadout','玩法配置',[{id:'default',name:'常规位置配置'},...b.loadoutOptions],b.loadoutId):''}
 ${b.combo?`<section class="companion-note" data-companion-section="combo"><b>${e(b.combo.title)}</b><p>${e(b.combo.plan)}</p>${b.combo.play?`<details data-companion-disclosure="duo-play"><summary>前期、接力与后期分工</summary>${duoPlayView(b.combo.play,{compact:true})}</details>`:''}<small>注意：${e(b.combo.risk)}</small></section>`:''}
 ${s.mode==='rift'?`<section class="companion-section companion-coach" data-companion-section="opponent">${matchupTargetView(data,s,enemyIds,opponentId,{status:matchupStatus})}${matchupPreparationView(matchupPreparation({data,selection:s,enemyIds,targetId:opponent?.id,publicContext,build:b}),data,{compact:true,plan:planKey(s)})}<h3>英雄速记</h3>${heroCoachView(coach,{compact:true})}<details data-companion-disclosure="coach"><summary>技能机制、对手应对与团战任务</summary>${heroCoachView(coach)}</details></section>`:''}
 ${s.mode==='rift'?`<details class="companion-section" data-companion-disclosure="matchups"><summary>对阵样本 · 当前英雄与位置</summary>${matchupView(data,b.reference,{compact:true})}</details>`:''}
  <section class="companion-section" data-companion-section="items"><h3>出装路线</h3>${coreComparison(b,data,key)}${b.reference?.core.length>1?select('core','核心路线',b.reference.core.map((c,i)=>({id:i,name:`${i+1}. ${corePurpose(c,data)} · ${c.items.map(id=>data.items[id]?.name||'旧版装备').join(' / ')}`})),b.selectedCoreIndex):''}<p class="companion-label">出门购买</p>${items(b.start)}${gearSelector(b,'start',{companion:true,plan:planKey(s)})}${b.granted.length?`<p class="companion-hint">位置任务自动给予：${e(b.granted.map(i=>i.name).join('、'))}，以客户端正式分路为准。</p>`:''}${b.early.length?`<p class="companion-hint">尽早补出：${e(b.early.map(i=>i.name).join('、'))}</p>`:''}<p class="companion-label">${b.reference?.laterBasis==='all-orders'?'核心三件 + 鞋子 + 自选后期':'成装顺序'} · 鞋子可提前买</p>${gearSelector(b,'boots',{companion:true,plan:planKey(s)})}${items(b.items,true)}${bottomQuestPlanControl(b,{companion:true,plan:planKey(s)})}${laterItemSelector(b,{companion:true,plan:planKey(s)})}${itemSetControls(data.champions.find(c=>c.id===s.id),b,data,{view:"companion",statuses:itemSetStatuses})}<div class="companion-conditions" aria-label="按实际对线调整">${conditions.map(([id,label])=>button('companion-condition',label,'',`small ${(s.conditions||[]).includes(id)?'active':''}`,`data-condition="${id}" data-plan="${key}" aria-pressed="${(s.conditions||[]).includes(id)}"`)).join('')}</div>${b.adjustments.map(a=>`<p class="companion-hint"><b>${e(a.title)}：</b>${e(a.text)}</p>`).join('')}</section>
 <section class="companion-section" data-companion-section="runes"><h3>${b.mode==='hex'?'海克斯强化':'完整符文'}</h3>${b.runePage?`${runeComparison(b,featured,runes,key,data)}${select('rune','全部完整符文方案',runeChoices,b.selectedRuneId)}<p class="companion-hint">${e(b.selectedRune?.when)}</p><div class="companion-rune-trees">${[[primary,b.runePage.selectedPerkIds.slice(0,4)],[secondary,b.runePage.selectedPerkIds.slice(4,6)]].map(([tree,ids])=>`<div><h4>${e(tree?.name)}</h4>${ids.map((id,i)=>`<div class="companion-rune ${tree===primary&&i===0?'keystone':''}" title="${e(gameDescription(runes.get(id)?.longDesc))}">${asset('rune',id,runes.get(id)?.name)}<span>${e(runes.get(id)?.name)}</span></div>`).join('')}</div>`).join('')}</div><p class="companion-shards">${b.runePage.selectedPerkIds.slice(6).map(id=>e(SHARDS[id])).join(' · ')}</p>`:`<p class="companion-hint">${b.mode==='hex'?'此模式不应用峡谷符文，强化按局内实际选项决定。':'当前方案没有可用的完整符文页。'}</p>`}</section>
 <section class="companion-section" data-companion-section="skills"><h3>加点与召唤师技能</h3>${b.skillMechanism?`<p class="companion-hint skill-mechanism">${e(b.skillMechanism)}</p>`:''}${b.skillChoices.length?select('skill','加点方案',[{id:'',name:'默认加点'},...b.skillChoices],s.skillId||''):''}<p class="companion-skill-priority">${b.priority?`优先 ${e(b.priority.split('').join(' › '))}`:'加点资料待补充'}${b.first?` · 前三级 ${e(b.first.split('').join(' › '))}`:''}</p>${b.skillOrder?`<div class="companion-skill-order" aria-label="${b.skillOrder.length} 个技能点参考">${[...b.skillOrder].map((k,i)=>`<span><small>${i+1}</small><b>${k}</b></span>`).join('')}</div>`:''}${summonerSelector(b,data,{compact:true,planKey:key})}<p class="companion-hint">${e(b.tips)}</p></section>
 ${b.selectionWarnings.map(w=>`<p class="callout warning">${e(w)}</p>`).join('')}${b.stale?'<p class="callout warning">该机制方案尚未完成当前资料版本复核。</p>':''}<details class="companion-source" data-companion-disclosure="source"><summary>${e(b.source)} · 参考版本 ${e(b.rulesPatch)} · 依据</summary><p>${e(b.sourceNote)}</p>${b.selectedSkill?`<p>${e(b.selectedSkill.when)}</p>`:''}${b.reference?button('link','查看 OP.GG 原始页面','arrow','quiet small',`data-url="${e(b.reference.sourceUrl)}"`):''}${s.mode==='hex'?button('companion-refresh',refreshing?'刷新中…':'刷新海克斯配置','refresh','small',`data-plan="${key}" ${refreshing?'disabled':''}`):''}</details>`;
}

export function companionView({data,client,slots,unassigned,enemy=[],bans=[],scope,soloRole,playerPosition=null,style,tab,results,generating,error,preparation,plan=preparation,favorites=[],configurationStatus={},applied=false,guideAutoShow=true,appVersion='',pairRefresh={},overlap,recovery}){
 const hero=id=>data.champions.find(c=>c.id===id),analysis=analyzeTeam(slots,data.champions),live=clientDraftStatus(client,slots,data.champions);
 const own=preparation?.own,b=preparation?.build;
 const assigned=CLIENT_POSITION_ROLES[String(client.session?.myTeam?.find(p=>p.cellId===client.session.localPlayerCellId)?.assignedPosition||'').toUpperCase()];
 const manual=manualPlayerSlot(slots,client.session?.localPlayerCellId);
 const roleSelect=`<label title="手动位置用于装备、符文与指引；任务权益仍按客户端分路">方案位置<select id="solo-role" class="select" aria-label="我的方案位置"><option value="">${assigned?'按客户端分路 · 取消手动':'未定 · 看各路'}</option>${ROLES.map(r=>`<option value="${r.id}" ${(manual?.role||playerPosition?.role||(own?.positionKnown?own.role:'')||soloRole||assigned)===r.id?'selected':''}>${r.name}</option>`).join('')}</select>${manual?button('position-auto','恢复','','quiet small','aria-label="恢复客户端位置" title="恢复客户端分路方案"'):''}</label>`;
 const current=`<section class="current-preparation companion-current" aria-label="本局英雄与位置">${own?`<div class="companion-current-hero">${portrait(hero(own.id))}<span><b>${e(hero(own.id)?.name)}</b><small>${own.positionKnown?roleName(b.role):`位置待确认 · 方案暂按${roleName(b.role)}`}${assigned&&b.role!==assigned?'<span class="position-note"> · 客户端分路：'+roleName(assigned)+'</span>':''}</small></span>${button('companion-current','本局方案','','quiet small')}</div>`:`<p>${live.hover.some(p=>p.local)?'预选 '+e(hero(live.hover.find(p=>p.local).id)?.name)+' · 尚未选定':'尚未选择英雄 · 可先看推荐'}</p>`}${roleSelect}</section>`;
 const controls=`<div class="companion-controls"><label>推荐范围<select id="companion-scope" class="select">${Object.entries(DRAFT_SCOPES).map(([id,s])=>`<option value="${id}" ${scope===id?'selected':''}>${s.name}</option>`).join('')}</select></label><label>玩法风格<select id="companion-style" class="select">${Object.entries(STYLES).map(([id,s])=>`<option value="${id}" ${style===id?'selected':''}>${s.name}</option>`).join('')}</select></label></div>`;
 const candidates=results.map((r,i)=>{
  const members=(r.scope==='solo'?r.slots.filter(s=>(r.targets||[]).includes(s.role)||!r.targets?.length&&s.champion):scopeSlots(r.slots,r.scope==='bot'?'bot':'party')).filter(s=>s.champion),combo=r.trio||r.duo;
  const adaptive=r.origin==='adaptive'?r.adaptive:null,jobs=resultMemberJobs(r,data);
  const caution=combo?.risk||adaptive?.failures[0]||r.strategy?.tradeoff||r.analysis?.warnings?.[0];
  return `<article class="companion-candidate"><div class="companion-members"><span class="companion-rank">${i+1}</span>${members.map(s=>`<button class="companion-hero" data-action="companion-preview" data-result-index="${i}" data-id="${s.champion}" data-role="${s.role}" ${combo?`data-combo="${e(combo.id)}"`:''}>${portrait(hero(s.champion))}<span><b>${e(hero(s.champion)?.name)}</b><small>${roleName(s.role)} · 查看方案</small></span></button>`).join('')}</div>${r.scope==='solo'?'':`<h4>${e(r.title)}</h4>`}${r.strategy?`<p class="companion-pairing"><b>玩法：</b>${e(r.strategy.label)}${r.strategy.matched===false&&r.strategy.preference?` · 偏好${e(r.strategy.preference)}，查看详细打法中的取舍`:''}</p>`:''}${jobs.length?resultActionsView(r,data):`<p>${e(r.strategy?.benefit||r.reason)}</p>`}${!jobs.length?r.contributions?.map(c=>`<p class="companion-pairing"><b>${members.length>1?e(c.name)+'：':''}${e(c.helps.slice(0,2).join('、'))}</b>${c.pairings?.[0]?`<br>${e(c.pairings[0])}`:''}${c.unusual?'<br>非常规位置，先约好补刀与经济。':''}</p>`).join('')||'':''}${pairStatisticsView(r.pairEvidence,data,{compact:true})}${opponentFitView(r.opponentFit,{compact:true})}${adaptive?`<p class="companion-pairing"><b>成立条件：</b>${e(adaptive.conditions[0])}</p><details class="more-builds" data-companion-disclosure="cooperation-${i}"><summary>完整成员分工、成立条件与资源安排</summary>${cooperationView(adaptive,data)}</details>`:''}${combo?.window?`<p><b>行动窗口：</b>${e(combo.window)}</p>`:''}${caution?`<p class="companion-caution"><b>注意：</b>${e(caution)}</p>`:''}<div class="companion-row-actions"><span>${r.origin==='creative'?'创意实验 · 未验证':adaptive?(adaptive.kind==='shared'?'共同分工 · 未经组合对局验证':'机制推导 · 未经组合对局验证'):'机制搭配参考'}</span>${button('result-detail','详细打法','','quiet small',`data-index="${i}"`)}</div></article>`;
 }).join('');
 const recommendations=`${controls}${pairRefreshView(data,pairRefreshTargets(slots,scope,soloRole),pairRefresh)}<p class="companion-hint">${scope==='solo'?soloRole?'按你的位置和队友已选英雄推荐。':'匹配没有分路信息，请先确认位置；当前分别看各路。':'在阵容页标记开黑朋友的位置，推荐会保留队友已选。'}</p><div class="companion-section-head"><h3>${scope==='solo'?'英雄推荐':'组合推荐'}${results.length?` · ${results.length} 套`:''}</h3>${button(results.length?'reroll':'recommend',generating?'计算中…':results.length?'换一批':'推荐','refresh','quiet small',generating?'disabled':'')}</div>${error?`<p class="callout warning">${e(error)}</p>`:''}${candidates||`<div class="companion-empty">${generating?'正在结合公开选人搭配…':'等待选人信息；也可以手动推荐。'}</div>`}<div class="companion-tools">${button('hero-pool','英雄池','','quiet small')}${button('exclusions','排除英雄','','quiet small')}${button('combination-library','组合库','','quiet small')}</div>`;
 const picks=(ids,label)=>`<section class="companion-section companion-public"><h3>${label}</h3><div class="companion-public-picks">${ids.length?ids.map(id=>`<span>${portrait(hero(id),'sm')}${e(hero(id)?.name)}</span>`).join(''):'<small>尚无公开信息</small>'}</div></section>`;
 const team=`${picks(enemy,'敌方公开已选')}${picks(bans,'公开禁选')}<p class="companion-hint">未分路的英雄需要手动安排，助手不会把队友自动塞到其他路。</p><div class="companion-roster">${slots.map(s=>`<div class="companion-roster-row">${portrait(hero(s.champion),'sm')}<span><b>${roleName(s.role)}</b><small>${e(hero(s.champion)?.name||'尚未安排')}</small></span>${button(s.champion?'move-slot':'pick-slot',s.champion?'换位':'选择','','quiet small',`data-role="${s.role}"`)}${scope!=='solo'?button('toggle-party',s.party?'我们':'队友','','small',`data-role="${s.role}"`):''}</div>`).join('')}</div>${unassigned.length?`<h3>已选 · 位置待确认</h3><div class="unassigned">${unassigned.map(p=>button('assign-import',portrait(hero(p.champion),'sm')+e(hero(p.champion)?.name)+(p.local?' · 你':''),'','small',`data-id="${p.champion}"`)).join('')}</div>`:''}<section class="companion-section"><h3>我方覆盖 · 已安排 ${analysis.known} / 5</h3><div class="companion-coverage">${[['frontline','前排'],['engage','开团'],['peel','保护'],['sustain','持续输出'],['poke','消耗'],['aoe','范围伤害']].map(([k,label])=>`<div><span>${label}</span><b>${analysis.known?(analysis.traits[k]?'已有 '+analysis.traits[k]:'尚缺'):'待确认'}</b></div>`).join('')}</div>${analysis.warnings.map(w=>`<p class="companion-caution">${e(w)}</p>`).join('')}${analysis.known?`<p class="companion-hint">${e(analysis.curve.label)} · ${e(analysis.control)}</p>`:''}${teamWindowsView(analysis)}</section>`;
 const ready=b?.runePage?(applied?'本次已应用 · 可在客户端核对':'方案已选好 · 符文待应用'):own?'方案已准备':plan?.intent?'预选方案已准备 · 尚未选定':'等待选好英雄';
 const compactReady=b?.runePage?(applied?'本次已应用':'符文待应用'):own?'方案已准备':plan?.intent?'预选未确定':'等待选英雄';
 const footer=`<footer class="companion-footer"><div class="companion-ready" role="status"><span class="companion-wide-label">${e(ready)}</span><span class="companion-short-label">${e(compactReady)}</span>${live.remaining!==null?` · 约剩 ${live.remaining} 秒`:''}</div><div class="companion-footer-actions">${b?.runePage?button('my-runes',`<span class="companion-wide-label">${applied?'重新应用符文':'替换'+e(hero(own.id)?.name)+'符文'}</span><span class="companion-short-label">${applied?'重新应用':'替换符文'}</span>`,'check','primary',`aria-label="替换${e(hero(own.id)?.name)}符文" data-id="${own.id}" ${client.connected&&client.phase==='ChampSelect'?'':'disabled'}`):''}${own?button('guide-current','<span class="companion-wide-label">本局指引</span><span class="companion-short-label">指引</span>','book','small','aria-label="打开本局指引"'):''}</div><small>${plan?.preview?'底部操作用于你在客户端已选的英雄。':guideAutoShow?'进入游戏自动呼出指引':'自动指引已关闭'} · ${button('guide-auto-show',guideAutoShow?'关闭自动':'开启自动','','quiet small')}</small><div class="companion-connection"><span>${client.connected?`${e(client.mode?.label||'选人中')}${overlap?' · 靠屏幕边缘':''}`:'连接中断 · 当前为旧参考'}</span>${button('window-info','窗口','','quiet small')}${button('sync','同步','','quiet small')}</div></footer>`;
 return `<div class="companion-shell" data-tab="${tab}" data-plan-preview="${!!plan?.preview}" data-client-position="${!!assigned}"><header class="companion-header"><div><b>开黑搭子</b><small>选人助手${appVersion?' · v'+e(appVersion):''}</small></div>${button('presentation-open','<span>字号</span>','settings','quiet small','aria-label="设置字号"')}${button('companion-full','<span class="companion-wide-label">展开助手</span><span class="companion-short-label">展开</span>','arrow','quiet small','aria-label="展开完整助手"')}</header><nav class="companion-tabs" aria-label="选人侧栏">${[['recommend','选英雄'],['plan','出装 · 符文'],['team','双方阵容']].map(([id,n])=>`<button data-action="companion-tab" data-tab="${id}" class="${tab===id?'active':''}" aria-pressed="${tab===id}">${id==='plan'?'<span class="companion-wide-label">出装 · 符文</span><span class="companion-short-label">方案</span>':n}</button>`).join('')}</nav>${current}<main class="companion-content" id="main">${stateRecoveryView(recovery)}${pickEligibilityView(localPickEligibility(client,slots,data.champions,{scope,soloRole,playerPosition}))}${tab==='plan'?companionPlanView(data,plan,favorites,configurationStatus):tab==='team'?team:recommendations}</main>${footer}</div>`;
}
