import {escape as e,asset,button} from './ui.mjs';
import {compareAugments} from './core/hex-compare.mjs';
import {validHexReference} from './core/builds.mjs';

export function renderHexSourceReference({data,hero,filtered=false}){
 const champion=data.champions.find(c=>c.id===hero),ref=data.hexBuilds?.[hero];
 if(!champion||!validHexReference(ref,champion,data,{allowOlder:true}))return `<div class="callout">这个英雄暂时使用机制出装，仍可查询全部强化。${button('refresh-hex','获取海克斯配置','refresh','small')}</div>`;
 const old=ref.patch!==data.patch,known=ref.augmentIds.map(id=>data.augments.find(a=>a.id===id)).filter(Boolean),missing=ref.augmentIds.length-known.length;
 return `<section class="panel hex-reference"><div class="panel-head"><div><h3>${e(champion.name)}的强化参考</h3><p>先在局内实际出现的选项中找，选不到也不用强求。</p></div><button class="chip ${filtered?'active':''}" data-action="hex-hero-filter">${filtered?'查看全部强化':'只看这些强化'}</button></div><div class="panel-body">${old?`<p class="callout warning">OP.GG ${e(ref.patch)} 旧版本参考 · 当前资料 ${e(data.patch)}；原方案保留，具体效果以局内为准。</p>`:''}<div class="chips">${known.map(a=>`<button class="chip" data-action="augment-detail" data-id="${a.id}">${e(a.name)}</button>`).join('')}</div>${missing?`<p class="bottom-note">原参考中 ${missing} 项强化未收录于当前资料，已保留其来源，不作为当前可选项。</p>`:''}<p class="bottom-note">OP.GG 英雄页面所列参考 · 全球海克斯大乱斗 · ${e(ref.patch)}。这份清单不预测胜率，已选强化之间的配合仍需结合效果判断。</p><button class="source-link" data-action="link" data-url="${e(ref.sourceUrl)}">查看来源 ↗</button></div></section>`;
}
export function renderHexComparison({data,hero,options,owned}){
 const rows=compareAugments({champion:data.champions.find(c=>c.id===hero),options,owned,augments:data.augments});
 const lookup=id=>data.augments.find(a=>a.id===id)?.name||'旧版强化';
 return `<section class="panel hex-comparison"><div class="panel-head"><div><h3>这次出现的强化，怎么选？</h3><p>搜索强化，打开详情后加入比较，最多 3 项。</p></div>${options.length?button('clear-compare','清空选项','','quiet small'):''}</div><div class="panel-body"><div class="section-label"><b>本局已选</b><small>由你手动确认，最多 6 项</small></div><div class="chips">${owned.map(id=>`<button class="chip active" data-action="remove-owned" data-id="${id}">${e(lookup(id))} ×</button>`).join('')||'<span class="muted">还没有标记已选强化</span>'}</div>${rows.length?`<div class="compare-grid">${rows.map(row=>`<article class="compare-card"><div class="augment-title">${asset('augment',row.id,row.name)}<b>${e(row.name)}</b><button data-action="compare-augment" data-id="${row.id}" aria-label="移出比较${e(row.name)}">×</button></div><p class="compare-effect">${e(row.description)}</p>${row.reasons.map(text=>`<p class="compare-reason">${e(text)}</p>`).join('')}${row.interactions.map(text=>`<p class="compare-interaction">${e(text)}</p>`).join('')}${row.cautions.map(text=>`<p class="compare-caution">${e(text)}</p>`).join('')}${button('own-augment','我选了这项','check','small',`data-id="${row.id}" ${owned.includes(row.id)?'disabled':''}`)}</article>`).join('')}</div>`:'<p class="bottom-note">这里比较局内实际出现的选项。左侧“备选”是想玩的清单，两者可以分别使用。</p>'}<p class="bottom-note">按效果文字和人工机制规则解释；不预测强化出现概率或组合胜率。确认收益前请核对游戏内当前数值。</p></div></section>`;
}
